/*
('id','name',rarity,unlock_level,'text','flavor_text')
ordered by level obtained on https://onestepfromeden.fandom.com/wiki/Artifacts
*/
INSERT INTO osfe_spells
VALUES 
    ('Bulwark ','Bulwark ',2,0,'Start battles with 40 Shield.','It\'s free shield estate.'),
    ('Citrine','Citrine',1,0,'Restore 0.2 Mana when Flame dmg is dealt.','flavor_text'),
    ('CoverFire','Cover Fire',3,0,'Gain 5 Attack Damage while Shuffling.','I\'m going in, cover me!'),
    ('HeartOfTheCards','Heart of the Cards',1,0,'Heal HP equal to the number of Spells in your deck at the start of battle.','It\'s free heal estate'),
    ('Moonstone','Moonstone',1,0,'Gain 0.2 Mana Regen for each Broken tile.','flavor_text'),
    ('SubTank','Second Soul',4,0,'On Death, Heal 600 HP. Only works once.','Let\'s do that again.'),
    ('PetDragon','Pet Dragon',4,2,'A dragon that shoots fireballs that leave Flames when you cast a spell.','flavor_text'),
    ('MoltenCore','Molten Core',3,4,'Gain 3 Shield whenever Flame dmg is dealt.','flavor_text'),
    ('Frostmail','Frostmail',4,5,'Fire a Frostbolt when you get hit. Lose 10 Spell Power.','Revenge is a dish best served Cold.'),
    ('Icing','Icing',3,7,'Fire a Frostbolt when you cast Jam.pngJam.','flavor_text'),
    ('SnowBoots','Snow Boots',1,7,'When Frost dmg is dealt also Root the target for 2 seconds.','flavor_text'),
    ('ColdPressedJuice','Cold Pressed Juice',3,8,'Heal 20 HP when Frost dmg is dealt.','Overpriced but delicious'),
    ('HardenedShields','Hardened Shields',2,9,'Defense also reduces Shield dmg.','flavor_text'),
    ('Acupuncture','Acupuncture',2,10,'Kunais apply Fragile.','flavor_text'),
    ('GripTape','Grip Tape',3,11,'Kunais cost 1 Mana but deal double damage','flavor_text'),
    ('MasonJar','Masonjar',3,11,'Apply Fragile to everyone whenever you go below 1 Mana.','flavor_text'),
    ('CassidyScarf','Cassidy\'s Scarf',2,12,'Stop time for 5 seconds when you go below 200 HP.','Anything\'s possible in a dream.'),
    ('Ninjutsu','Ninjutsu',4,13,'50% Chance to add a Kunai to your deck when you hit a target with a Kunai.','flavor_text'),
    ('ImmuneSystem','Immune System',3,14,'Gain 20 Shield whenever Poison dmg is dealt.','flavor_text'),
    ('ShadowToxin','Shadow Toxin',3,14,'Kunais apply 20 Poison.','flavor_text'),
    ('ResistantStrain','Resistant Strain',2,16,'Poison never drops below 20, including on yourself.','I\'ll wait.'),
    ('ChaosFrag','Chaos Fragment',2,17,'Gain random effects at the start of battle.','Seems a bit buggy.'),
    ('DartFrog','Dart Frog',4,18,'Apply 4 Poison when a spell hits an enemy.','Jerro jerro'),
    ('Thorn','Thorn',4,18,'Gain 3 Spell Power, but Shield decays slowly.','How irregular'),
    ('UnicornBomb','Unicorn Bomb',4,19,'Hit enemies with 40 dmg rainbows that remove a buff at the start of battle.','Don\'t believe unicorns are real.'),
    ('Vaccine','Vaccine',2,19,'Heal 160 HP and gain 80 Poison at the start of battle.','flavor_text'),
    ('Flechette','Flechette',2,20,'Weapon hits ricochet and hit another enemy.','flavor_text'),
    ('PetKitty','Pet Kitty',4,21,'A kitty that fires Frost shots three ways when you cast a spell.','flavor_text'),
    ('PocketSand','Pocket Sand',3,22,'Gain invincibility for 1 second when you Shuffle.','Shuffle to dodge.'),
    ('PhasePlates','Phase Plates',4,23,'Gain invincibility for 0.75 second and Fragile when you take dmg.','I just felt a slight pinch.'),
    ('Daffodil','Daffodil',3,33,'Gain 2 Removals, Lose 200 Max HP.','flavor_text'),
    ('Lilac','Lilac',4,33,'Gain 2 Upgraders. Lose 300 Max HP.','flavor_text'),
    ('SpellthiefLicense','Spellthief License',3,34,'Heal 200 HP when you Remove a Spell.','flavor_text'),
    ('Stoplight','Stoplight',1,35,'Apply Root for 1 second to all enemies on Trinity Cast','flavor_text'),
    ('Tessellate','Tessellate',1,35,'Gain 1 Trinity when you Shuffle.','flavor_text'),
    ('CandyWrapper','Candy Wrapper',2,38,'Wrap vertically around the field.','flavor_text'),
    ('Mother','Mother',4,39,'All Spells give Flow Stacks. Lose 0.2 Mana Regen.','flavor_text'),
    ('Trifrost','Trifrost',3,39,'Apply Frost to a random enemy on Trinity Cast.','Connects Midgard, Asgard, and Eden.'),
    ('DuelDisk','Duel Disk',4,40,'Shuffles are instant but add 3 Jam to your deck. You can\'t manually Shuffle.','Screw the rules, I have money!'),
    ('Goldfish','Goldfish',3,40,'Increase Luck by 15.','flavor_text'),
    ('PetFox','Pet Fox',3,41,'A fox that shoots a slow shot that applies Root when you Shuffle.','flavor_text'),
    ('Transcendence','Transcendence',4,42,'Set Max HP to 1. Gain 1000 Shield at the start of battle and lose less shield on Shuffle.','Become 1 with everything.'),
/* no levels entered in below blob */
    ('ThreeDPrinter','3D Printer',1,unlock_level,'Add 1 Kunai to your deck when you Shuffle.','Let me just calibrate this'),
    ('AdaptiveArmor','Adaptive Armor',1,unlock_level,'Gain 10 Defense for 1 second when you get hit.','flavor_text'),
    ('Adrenaline','Adrenaline',2,unlock_level,'If below 50% health, start battles with 3 Spell Power and Haste.','flavor_text'),
    ('Aether','Aether',3,unlock_level,'Gain Defense equal to your current Mana.','flavor_text'),
    ('Amethyst','Amethyst',2,unlock_level,'Restore 0.1 Mana when you cast a spell.','Made in the prime kindergarten'),
    ('Anthrax','Anthrax',3,unlock_level,'Applying Poison deals 5 dmg.','flavor_text'),
    ('Anvil','Anvil',1,unlock_level,'Gain 13 Shield when you take Flame damage.','flavor_text'),
    ('Bandage','Bandage',2,unlock_level,'Heal 50 to 200 HP.','Let me just wrap this around my arm and I\'ll be fine.'),
    ('BazsWhip','Baz\'s Whip',4,unlock_level,'4% Chance to strike with 100 dmg Thunder when you hit a target','You can see the crackle of electricity from this whip. Can you feel the storm? It\'s coming.'),
    ('Beaker','Beaker',2,unlock_level,'While you have Fragile gain 0.3 Mana Regen. Gain 1 Fragile at the start of battle.','flavor_text'),
    ('Beret','Beret',4,unlock_level,'Drop Money when you take dmg. Your Max HP equals your Money.','flavor_text'),
    ('Bismuth','Bismuth',2,unlock_level,'Gain 3 Shield when you cast a spell.','Made of honor'),
    ('BlazeOfGlory','Blaze Of Glory',1,unlock_level,'Dead enemies leave a Flame behind.','flavor_text'),
    ('BloodMoney','Blood Money',3,unlock_level,'Gain 20 Money when you kill a Hostage.','flavor_text'),
    ('BlueBlood','Blue Blood',1,unlock_level,'Start battles with full Mana.','Blue blood burns bluetifully'),
    ('BlueFlame','Blue Flame',2,unlock_level,'Lose 1 Max Mana. Gain 0.3 Mana Regen.','flavor_text'),
    ('BlueberryJam','Blueberry Jam',2,unlock_level,'Jam cards cost 1 Mana instead of 2.','flavor_text'),
    ('BoltAction','Bolt Action',1,unlock_level,'Shuffle artifacts trigger when you kill an enemy.','flavor_text'),
    ('Bubble','Bubble',1,unlock_level,'While you have Flow gain 5 Defense.','flavor_text'),
    ('CardThrower','Card Thrower',2,unlock_level,'Deal 20 dmg to a random enemy when you Consume a card.','flavor_text'),
    ('CensorBar','Censor Bar',1,unlock_level,'Gain 30 Shield when you Channel.','flavor_text'),
    ('Chalice','Chalice',3,unlock_level,'Gain 1 Mana Regen while Mana is below 1.','Harmony'),
    ('ChocoMintChip','Choco Mint Chip',1,unlock_level,'Slow enemies when Frost is applied.','The best flavor.'),
    ('CobraCare','Cobra Care',2,unlock_level,'Heal for 40 HP when you take a spell.','flavor_text'),
    ('ColdBlooded','Cold Blooded',2,unlock_level,'All enemies start with 1 Frost.','Reptilia'),
    ('CoolShoes','Cool Shoes',4,unlock_level,'Restore 0.1 Mana on move.','Better nerf Selicy.'),
    ('CreditCard','Credit Card',2,unlock_level,'Gain 100 Money.','Your mom\'s'),
    ('Cryophage','Cryophage',1,unlock_level,'50% chance to apply a Frost stack when Poison damage is dealt.','flavor_text'),
    ('Curacao','Curacao',1,unlock_level,'Apply 40 Poison to a random enemy when you Trinity Cast.','flavor_text'),
    ('Delta','Delta',1,unlock_level,'Gain 3 Flow when you Trinity Cast','flavor_text'),
    ('DoubleEdge','Double Edge',2,unlock_level,'Gain 3 Spell Power. Lose 3 Defense.','flavor_text'),
    ('DoubleMint','Double Mint',4,unlock_level,'Apply 1 Frost after Frost dmg is dealt. If you have Fragile do it after Frost is applied instead.','flavor_text'),
    ('DuctTape','Duct Tape',2,unlock_level,'Lose 25% instead of 40% of your Shield when you Shuffle.','That\'s a lotta damage!'),
    ('Elysium','Elysium',3,unlock_level,'50% chance to trigger Flow Cast twice.','flavor_text'),
    ('EmptyBottle','Empty Bottle',1,unlock_level,'text','It\'s dangerous to go alone! Take this.'),
    ('Eschaton','Eschaton',4,unlock_level,'Gain 1 Shield when you move.','Reva\'s shield.'),
    ('ExplosiveTendons','Explosive Tendons',1,unlock_level,'Enemies have a chance to explode on death, dealing 40 dmg to surrounding tiles.','flavor_text'),
    ('Feather','Feather',2,unlock_level,'Gain Spell Power equal to to half your Fragile stacks.','flavor_text'),
    ('FlakJacket','Flak Jacket',3,unlock_level,'Fire a 20 dmg shot when you get hit.','flavor_text'),
    ('FlashLoader','Flash Loader',3,unlock_level,'Your first Shuffle each battle is instant.','flavor_text'),
    ('Fragment','Fragment',3,unlock_level,'Structures fire a 40 dmg shot when they are destroyed.','flavor_text'),
    ('FreezerBurn','Freezer Burn',4,unlock_level,'Create a Flame when Frost dmg is dealt.','How old is this...?'),
    ('Gelatin','Gelatin',2,unlock_level,'Gain 20 Shield when you cast Jam.','flavor_text'),
    ('GhostCostume','Ghost Costume',3,unlock_level,'Gain invincibility for 4 seconds at the start of battle.','Boo! urns.'),
    ('GiantArmor','Giant Armor',3,unlock_level,'Gain 10 Defense. Lose 0.3 Mana Regen.','The legend never dies.'),
    ('GlassCannon','Glass Cannon',1,unlock_level,'Gain 4 Spell Power and 1 Fragile at the start of battle.','flavor_text'),
    ('Champagne','Glass Flute',2,unlock_level,'Apply 1 Fragile to all enemies at the start of battle.','flavor_text'),
    ('GoldenCat','Golden Cat',2,unlock_level,'Gain 1 Luck when you take a spell.','flavor_text'),
    ('Granite','Granite',2,unlock_level,'Gain 10 Shield whenever a Tile is Broken.','flavor_text'),
    ('Harpoon','Harpoon',1,unlock_level,'While you have Flow gain 4 Spell Power.','flavor_text'),
    ('HeartOfGold','Heart of Gold',4,unlock_level,'Heal to full health, lose 5 Defense. Gain 1 Spell Power and Attack Damage.','flavor_text'),
    ('HexBadge','Hex Badge',3,unlock_level,'Gain 40 Shield when you Summon something.','flavor_text'),
    ('HitSeeker','Hit Seeker',1,unlock_level,'10% Chance to launch a 40 dmg missile when a spell hits an enemy.','Risk of pain.'),
    ('HoningSteel','Honing Steel',2,unlock_level,'Gain 2 Attack Damage.','flavor_text'),
    ('IceFloe','Ice Floe',1,unlock_level,'Gain 2 Flow stacks when Frost dmg is dealt.','flavor_text'),
    ('IceSculpture','Ice Sculpture',1,unlock_level,'Apply Fragile when Frost damage is dealt.','flavor_text'),
    ('Kabob','Kabob',1,unlock_level,'Gain 30 Shield and 1 Spell Power until the end of the battle when you kill an enemy.','flavor_text'),
    ('KineticShield','Kinetic Shield',2,unlock_level,'Gain 2 ShieldShield when you get hit.','flavor_text'),
    ('KnifeBelt','Knife Belt',1,unlock_level,'Add 2 Kunais to your deck at the start of battle.','Stop calling me a mall ninja!'),
    ('LaserPointer','Laser Pointer',2,unlock_level,'25% Chance to also shoot a laser when you cast a spell.','Go for the eyes!'),
    ('LifeJacket','Life Jacket',1,unlock_level,'Gain 10 Defense while Shuffling.','flavor_text'),
    ('Lily','Lily',3,unlock_level,'Gain 0.3 Mana Regen. Lose 300 Max HP.','flavor_text'),
    ('LinkCable','Link Cable',3,unlock_level,'Apply Link for 7 seconds to a random enemy at the start of battle.','1v1 me bro.'),
    ('LongSleeves','Long Sleeves',3,unlock_level,'Add a Kunai to your deck when you get hit.','flavor_text'),
    ('LuckBox','Luck Box',2,unlock_level,'Gain 3 Luck.','Never lucky.'),
    ('LuckyCoin','Lucky Coin',3,unlock_level,'50% Chance to gain 200 Money or lose 200 Money.','flavor_text'),
    ('Luna','Luna',3,unlock_level,'Restore 0.5 Mana when On Flow is triggered.','flavor_text'),
    ('GunnerFrontAll','M1 Liofire (Artifact)',2,unlock_level,'Replace your weapon with the M1 Liofire.','flavor_text'),
    ('GunnerHoming','M2 Hunter Seeker (Artifact)',2,unlock_level,'Replace your weapon with the M2 Hunter Seeker.','flavor_text'),
    ('MagnifyingGlass','Magnifying Glass',2,unlock_level,'Fragile increases dmg by 200% instead of 150%.','flavor_text'),
    ('ManaGem','Mana Gem',2,unlock_level,'Gain 1 Max Mana.','flavor_text'),
    ('ManaVein','Mana Vein',1,unlock_level,'Gain 0.1 Mana Regen.','I can feel it coursing through my veins!'),
    ('ManaJam','Manajam',1,unlock_level,'Gain 0.3 Mana Regen. Add 3 Jams to your deck at the start of battle.','flavor_text'),
    ('MeatShield','Meat Shield',3,unlock_level,'Gain 10 Shield when you Consume a card.','flavor_text'),
    ('Medkit','Medkit',3,unlock_level,'Health-iconHeal 250 HP.','I don\'t need it...'),
    ('MeritBadge','Merit Badge',4,unlock_level,'Permanently gain 1 Spell Power when you save a Hostage.','Scout\'s honor'),
    ('MicroMissiles','Micro Missiles',1,unlock_level,'50% Chance to launch a missile with weapon dmg when you use your weapon.','flavor_text'),
    ('MiningRig','Mining Rig',2,unlock_level,'Gain 3 Money after every battle.','This is good for bitcoin because'),
    ('MintTea','Mint Tea',1,unlock_level,'text','flavor_text'),
    ('Miracle','Miracle',3,unlock_level,'text','flavor_text'),
    ('Mirror','Mirror',4,unlock_level,'text','flavor_text'),
    ('Mitosis','Mitosis',2,unlock_level,'text','flavor_text'),
    ('Mjolnir','Mjolnir',4,unlock_level,'text','flavor_text'),
    ('Monocle','Monocle',1,unlock_level,'text','flavor_text'),
    ('Multitool','Multitool',1,unlock_level,'text','flavor_text'),
    ('MuzzleBrake','Muzzle Brake',1,unlock_level,'text','flavor_text'),
    ('NerveGas','Nerve Gas',1,unlock_level,'text','flavor_text'),
    ('PantherHabit','Panther Habit',2,unlock_level,'text','flavor_text'),
    ('PaperWallet','Paper Wallet',2,unlock_level,'text','flavor_text'),
    ('Pendulum','Pendulum',1,unlock_level,'text','flavor_text'),
    ('PetLiger','Pet Liger',4,unlock_level,'text','flavor_text'),
    ('PetPuppy','Pet Puppy',3,unlock_level,'text','flavor_text'),
    ('PetTurtle','Pet Turtle',3,unlock_level,'text','flavor_text'),
    ('PiggyBank','Piggy Bank',2,unlock_level,'text','flavor_text'),
    ('Pinwheel','Pinwheel',1,unlock_level,'text','flavor_text'),
    ('PocketWatch','Pocket Watch',3,unlock_level,'text','flavor_text'),
    ('PoisonVial','Poison Vial',1,unlock_level,'text','flavor_text'),
    ('PowerShard','Power Shard',2,unlock_level,'text','flavor_text'),
    ('RemoveOne','Remove One',3,unlock_level,'text','flavor_text'),
    ('RescueBadge','Rescue Badge',3,unlock_level,'text','flavor_text'),
    ('Riffle','Riffle',1,unlock_level,'text','flavor_text'),
    ('RockTumbler','Rock Tumbler',1,unlock_level,'text','flavor_text'),
    ('RollerBlades','Roller Blades',3,unlock_level,'text','flavor_text'),
    ('Rose','Rose',2,unlock_level,'text','flavor_text'),
    ('Ruby','Ruby',3,unlock_level,'text','flavor_text'),
    ('SaigonArmor','Saigon Armor',3,unlock_level,'text','flavor_text'),
    ('Satellite','Satellite',3,unlock_level,'text','flavor_text'),
    ('Scales','Scales',1,unlock_level,'text','flavor_text'),
    ('SecondBreakfast','Second Breakfast',1,unlock_level,'text','flavor_text'),
    ('ShieldBattery','Shield Battery',2,unlock_level,'text','flavor_text'),
    ('Sinkhole','Sinkhole',1,unlock_level,'text','flavor_text'),
    ('SoulFood','Soul Food',3,unlock_level,'text','flavor_text'),
    ('PetSoulGun','Soul Gun',3,unlock_level,'text','flavor_text'),
    ('SpeedLoader','Speed Loader',3,unlock_level,'text','flavor_text'),
    ('SpikeProtein','Spike Protein',1,unlock_level,'text','flavor_text'),
    ('Static','Static',2,unlock_level,'text','flavor_text'),
    ('StepDrone','Step Drone',3,unlock_level,'text','flavor_text'),
    ('Stimpack','Stimpack',2,unlock_level,'text','flavor_text'),
    ('SugarGlass','Sugar Glass',1,unlock_level,'text','flavor_text'),
    ('Sunglasses','Sunglasses',2,unlock_level,'text','flavor_text'),
    ('SurvivalKit','Survival Kit',1,unlock_level,'text','flavor_text'),
    ('Symbiosis','Symbiosis',1,unlock_level,'text','flavor_text'),
    ('Thermite','Thermite',3,unlock_level,'text','flavor_text'),
    ('Thermophage','Thermophage',1,unlock_level,'text','flavor_text'),
    ('Thornmail','Thornmail',1,unlock_level,'text','flavor_text'),
    ('TightPants','Tight Pants',4,unlock_level,'text','flavor_text'),
    ('Tinder','Tinder',4,unlock_level,'text','flavor_text'),
    ('Transmission','Transmission',2,unlock_level,'text','flavor_text'),
    ('TrapCard','Trap Card',4,unlock_level,'text','flavor_text'),
    ('Trinket','Trinket',3,unlock_level,'text','flavor_text'),
    ('Trident','Trident',1,unlock_level,'text','flavor_text'),
    ('Tutu','Tutu',1,unlock_level,'text','flavor_text'),
    ('Umbrella','Umbrella',1,unlock_level,'text','flavor_text'),
    ('Undershirt','Undershirt',2,unlock_level,'text','flavor_text'),
    ('UpgradeOne','Upgrade One',3,unlock_level,'text','flavor_text'),
    ('Uranium','Uranium',3,unlock_level,'text','flavor_text'),
    ('VGunMod','VGun',4,unlock_level,'text','flavor_text'),
    ('Violet','Violet',2,unlock_level,'text','flavor_text'),
    ('ViralTransmitter','Viral Transmitter',1,unlock_level,'text','flavor_text'),
    ('Virtue','Virtue',3,unlock_level,'text','flavor_text'),
    ('WaterWheel','Water Wheel',1,unlock_level,'text','flavor_text'),
    ('Wings','Wings',4,unlock_level,'text','flavor_text'),
    ('XD40','XD-40',1,unlock_level,'text','flavor_text'),
    ('ZCell','Z-Cell',2,unlock_level,'text','flavor_text')
    ;

/* no unlock levels entered on the wiki for these
    ('ThreeDPrinter','3D Printer',1,unlock_level,'text','flavor_text'),
    ('AdaptiveArmor','Adaptive Armor',1,unlock_level,'text','flavor_text'),
    ('Adrenaline','Adrenaline',2,unlock_level,'text','flavor_text'),
    ('Aether','Aether',3,unlock_level,'text','flavor_text'),
    ('Amethyst','Amethyst',2,unlock_level,'text','flavor_text'),
    ('Anthrax','Anthrax',3,unlock_level,'text','flavor_text'),
    ('Anvil','Anvil',1,unlock_level,'text','flavor_text'),
    ('Bandage','Bandage',2,unlock_level,'text','flavor_text'),
    ('BazsWhip','Baz\'s Whip',4,unlock_level,'text','flavor_text'),
    ('Beaker','Beaker',2,unlock_level,'text','flavor_text'),
    ('Beret','Beret',4,unlock_level,'text','flavor_text'),
    ('Bismuth','Bismuth',2,unlock_level,'text','flavor_text'),
    ('BlazeOfGlory','Blaze Of Glory',1,unlock_level,'text','flavor_text'),
    ('BloodMoney','Blood Money',3,unlock_level,'text','flavor_text'),
    ('BlueBlood','Blue Blood',1,unlock_level,'text','flavor_text'),
    ('BlueFlame','Blue Flame',2,unlock_level,'text','flavor_text'),
    ('BlueberryJam','Blueberry Jam',2,unlock_level,'text','flavor_text'),
    ('BoltAction','Bolt Action',1,unlock_level,'text','flavor_text'),
    ('Bubble','Bubble',1,unlock_level,'text','flavor_text'),
    ('CardThrower','Card Thrower',2,unlock_level,'text','flavor_text'),
    ('CensorBar','Censor Bar',1,unlock_level,'text','flavor_text'),
    ('Chalice','Chalice',3,unlock_level,'text','flavor_text'),
    ('ChocoMintChip','Choco Mint Chip',1,unlock_level,'text','flavor_text'),
    ('CobraCare','Cobra Care',2,unlock_level,'text','flavor_text'),
    ('ColdBlooded','Cold Blooded',2,unlock_level,'text','flavor_text'),
    ('CoolShoes','Cool Shoes',4,unlock_level,'text','flavor_text'),
    ('CreditCard','Credit Card',2,unlock_level,'text','flavor_text'),
    ('Cryophage','Cryophage',1,unlock_level,'text','flavor_text'),
    ('Curacao','Curacao',1,unlock_level,'text','flavor_text'),
    ('Delta','Delta',1,unlock_level,'text','flavor_text'),
    ('DoubleEdge','Double Edge',2,unlock_level,'text','flavor_text'),
    ('DoubleMint','Double Mint',4,unlock_level,'text','flavor_text'),
    ('DuctTape','Duct Tape',2,unlock_level,'text','flavor_text'),
    ('Elysium','Elysium',3,unlock_level,'text','flavor_text'),
    ('EmptyBottle','Empty Bottle',1,unlock_level,'text','flavor_text'),
    ('Eschaton','Eschaton',4,unlock_level,'text','flavor_text'),
    ('ExplosiveTendons','Explosive Tendons',1,unlock_level,'text','flavor_text'),
    ('Feather','Feather',2,unlock_level,'text','flavor_text'),
    ('FlakJacket','Flak Jacket',3,unlock_level,'text','flavor_text'),
    ('FlashLoader','Flash Loader',3,unlock_level,'text','flavor_text'),
    ('Fragment','Fragment',3,unlock_level,'text','flavor_text'),
    ('FreezerBurn','Freezer Burn',4,unlock_level,'text','flavor_text'),
    ('Gelatin','Gelatin',2,unlock_level,'text','flavor_text'),
    ('GhostCostume','Ghost Costume',3,unlock_level,'text','flavor_text'),
    ('GiantArmor','Giant Armor',3,unlock_level,'text','flavor_text'),
    ('GlassCannon','Glass Cannon',1,unlock_level,'text','flavor_text'),
    ('Champagne','Glass Flute',2,unlock_level,'text','flavor_text'),
    ('GoldenCat','Golden Cat',2,unlock_level,'text','flavor_text'),
    ('Granite','Granite',2,unlock_level,'text','flavor_text'),
    ('Harpoon','Harpoon',1,unlock_level,'text','flavor_text'),
    ('HeartOfGold','Heart of Gold',4,unlock_level,'text','flavor_text'),
    ('HexBadge','Hex Badge',3,unlock_level,'text','flavor_text'),
    ('HitSeeker','Hit Seeker',1,unlock_level,'text','flavor_text'),
    ('HoningSteel','Honing Steel',2,unlock_level,'text','flavor_text'),
    ('IceFloe','Ice Floe',1,unlock_level,'text','flavor_text'),
    ('IceSculpture','Ice Sculpture',1,unlock_level,'text','flavor_text'),
    ('Kabob','Kabob',1,unlock_level,'text','flavor_text'),
    ('KineticShield','Kinetic Shield',2,unlock_level,'text','flavor_text'),
    ('KnifeBelt','Knife Belt',1,unlock_level,'text','flavor_text'),
    ('LaserPointer','Laser Pointer',2,unlock_level,'text','flavor_text'),
    ('LifeJacket','Life Jacket',1,unlock_level,'text','flavor_text'),
    ('Lily','Lily',3,unlock_level,'text','flavor_text'),
    ('LinkCable','Link Cable',3,unlock_level,'text','flavor_text'),
    ('LongSleeves','Long Sleeves',3,unlock_level,'text','flavor_text'),
    ('LuckBox','Luck Box',2,unlock_level,'text','flavor_text'),
    ('LuckyCoin','Lucky Coin',3,unlock_level,'text','flavor_text'),
    ('Luna','Luna',3,unlock_level,'text','flavor_text'),
    ('GunnerFrontAll','M1 Liofire (Artifact)',2,unlock_level,'text','flavor_text'),
    ('GunnerHoming','M2 Hunter Seeker (Artifact)',2,unlock_level,'text','flavor_text'),
    ('MagnifyingGlass','Magnifying Glass',2,unlock_level,'text','flavor_text'),
    ('ManaGem','Mana Gem',2,unlock_level,'text','flavor_text'),
    ('ManaVein','Mana Vein',1,unlock_level,'text','flavor_text'),
    ('ManaJam','Manajam',1,unlock_level,'text','flavor_text'),
    ('MeatShield','Meat Shield',3,unlock_level,'text','flavor_text'),
    ('Medkit','Medkit',3,unlock_level,'text','flavor_text'),
    ('MeritBadge','Merit Badge',4,unlock_level,'text','flavor_text'),
    ('MicroMissiles','Micro Missiles',1,unlock_level,'text','flavor_text'),
    ('MiningRig','Mining Rig',2,unlock_level,'text','flavor_text'),
    ('MintTea','Mint Tea',1,unlock_level,'text','flavor_text'),
    ('Miracle','Miracle',3,unlock_level,'text','flavor_text'),
    ('Mirror','Mirror',4,unlock_level,'text','flavor_text'),
    ('Mitosis','Mitosis',2,unlock_level,'text','flavor_text'),
    ('Mjolnir','Mjolnir',4,unlock_level,'text','flavor_text'),
    ('Monocle','Monocle',1,unlock_level,'text','flavor_text'),
    ('Multitool','Multitool',1,unlock_level,'text','flavor_text'),
    ('MuzzleBrake','Muzzle Brake',1,unlock_level,'text','flavor_text'),
    ('NerveGas','Nerve Gas',1,unlock_level,'text','flavor_text'),
    ('PantherHabit','Panther Habit',2,unlock_level,'text','flavor_text'),
    ('PaperWallet','Paper Wallet',2,unlock_level,'text','flavor_text'),
    ('Pendulum','Pendulum',1,unlock_level,'text','flavor_text'),
    ('PetLiger','Pet Liger',4,unlock_level,'text','flavor_text'),
    ('PetPuppy','Pet Puppy',3,unlock_level,'text','flavor_text'),
    ('PetTurtle','Pet Turtle',3,unlock_level,'text','flavor_text'),
    ('PiggyBank','Piggy Bank',2,unlock_level,'text','flavor_text'),
    ('Pinwheel','Pinwheel',1,unlock_level,'text','flavor_text'),
    ('PocketWatch','Pocket Watch',3,unlock_level,'text','flavor_text'),
    ('PoisonVial','Poison Vial',1,unlock_level,'text','flavor_text'),
    ('PowerShard','Power Shard',2,unlock_level,'text','flavor_text'),
    ('RemoveOne','Remove One',3,unlock_level,'text','flavor_text'),
    ('RescueBadge','Rescue Badge',3,unlock_level,'text','flavor_text'),
    ('Riffle','Riffle',1,unlock_level,'text','flavor_text'),
    ('RockTumbler','Rock Tumbler',1,unlock_level,'text','flavor_text'),
    ('RollerBlades','Roller Blades',3,unlock_level,'text','flavor_text'),
    ('Rose','Rose',2,unlock_level,'text','flavor_text'),
    ('Ruby','Ruby',3,unlock_level,'text','flavor_text'),
    ('SaigonArmor','Saigon Armor',3,unlock_level,'text','flavor_text'),
    ('Satellite','Satellite',3,unlock_level,'text','flavor_text'),
    ('Scales','Scales',1,unlock_level,'text','flavor_text'),
    ('SecondBreakfast','Second Breakfast',1,unlock_level,'text','flavor_text'),
    ('ShieldBattery','Shield Battery',2,unlock_level,'text','flavor_text'),
    ('Sinkhole','Sinkhole',1,unlock_level,'text','flavor_text'),
    ('SoulFood','Soul Food',3,unlock_level,'text','flavor_text'),
    ('PetSoulGun','Soul Gun',3,unlock_level,'text','flavor_text'),
    ('SpeedLoader','Speed Loader',3,unlock_level,'text','flavor_text'),
    ('SpikeProtein','Spike Protein',1,unlock_level,'text','flavor_text'),
    ('Static','Static',2,unlock_level,'text','flavor_text'),
    ('StepDrone','Step Drone',3,unlock_level,'text','flavor_text'),
    ('Stimpack','Stimpack',2,unlock_level,'text','flavor_text'),
    ('SugarGlass','Sugar Glass',1,unlock_level,'text','flavor_text'),
    ('Sunglasses','Sunglasses',2,unlock_level,'text','flavor_text'),
    ('SurvivalKit','Survival Kit',1,unlock_level,'text','flavor_text'),
    ('Symbiosis','Symbiosis',1,unlock_level,'text','flavor_text'),
    ('Thermite','Thermite',3,unlock_level,'text','flavor_text'),
    ('Thermophage','Thermophage',1,unlock_level,'text','flavor_text'),
    ('Thornmail','Thornmail',1,unlock_level,'text','flavor_text'),
    ('TightPants','Tight Pants',4,unlock_level,'text','flavor_text'),
    ('Tinder','Tinder',4,unlock_level,'text','flavor_text'),
    ('Transmission','Transmission',2,unlock_level,'text','flavor_text'),
    ('TrapCard','Trap Card',4,unlock_level,'text','flavor_text'),
    ('Trinket','Trinket',3,unlock_level,'text','flavor_text'),
    ('Trident','Trident',1,unlock_level,'text','flavor_text'),
    ('Tutu','Tutu',1,unlock_level,'text','flavor_text'),
    ('Umbrella','Umbrella',1,unlock_level,'text','flavor_text'),
    ('Undershirt','Undershirt',2,unlock_level,'text','flavor_text'),
    ('UpgradeOne','Upgrade One',3,unlock_level,'text','flavor_text'),
    ('Uranium','Uranium',3,unlock_level,'text','flavor_text'),
    ('VGunMod','VGun',4,unlock_level,'text','flavor_text'),
    ('Violet','Violet',2,unlock_level,'text','flavor_text'),
    ('ViralTransmitter','Viral Transmitter',1,unlock_level,'text','flavor_text'),
    ('Virtue','Virtue',3,unlock_level,'text','flavor_text'),
    ('WaterWheel','Water Wheel',1,unlock_level,'text','flavor_text'),
    ('Wings','Wings',4,unlock_level,'text','flavor_text'),
    ('XD40','XD-40',1,unlock_level,'text','flavor_text'),
    ('ZCell','Z-Cell',2,unlock_level,'text','flavor_text')*/


