/*
Maybe like, a quarter of the spells so far: https://onestepfromeden.fandom.com/wiki/Spells
Done in order of level obtained, alphabetically
('id','name',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text')
*/
	/*
    Anima 1
	Convergence 2
	Doublelift 3
	Glimmer 4
	Hearth 5
	Hexawan 6
	Kinesys 7
	Miseri 8
	Phalanx 9
	Slashfik 10
    None 11
    */
INSERT INTO osfe_spells
VALUES
	('Absorb','Absorb',3,120,9,0,0,1,0,'Hit 4 tiles away, if this hits catch to gain 80 Shield.pngShield.','flavor_text'),
    ('AcidRain','Acid Rain',1,20,8,0,0,2,0,'Rain arrows in a 3x3 area that apply 20 Poison.pngPoison Channel.pnguntil you move.','Some stay dry and others feel the pain.'),
    ('Air Slash','Air Slash',2,40,7,0,0,1,0,'Wide piercing shot Relocation.pngpushes targets back 1 tile.','flavor_text'),
    ('Align','Align',0,0,7,0,0,2,0,'Wide shot Relocation.pngteleports target 4 tiles away.','King of the jungle.'),
    ('Ambush','Ambush',2,200,5,0,0,4,0,'Hit 4 tiles away. When this hits, TileBreak.pngBreak tiles in a cross.','flavor_text'),
    ('Anubis','Anubis',1,0,8,0,0,1,0,'Apply 40 Poison.pngPoison to all enemies.','flavor_text'),
    ('Barrier','Barrier',1,0,5,0,0,2,0,'Gain 30 Shield.pngShield (+5) for each Flow.pngFlow you have. Gain 1 Flow.pngFlow','flavor_text'),
    ('SumBeacon','Beacon',2,80,6,0,0,2,0,'Summon a Beacon that calls down Flame.pngFlames every 3 seconds.','flavor_text'),
    ('Blackout','Blackout',2,99,10,0,0,4,0,'Darken the screen and slash all enemies.','In the darkness, you\'re all alone.'),
    ('BladeBayToss','Blade Bay',2,50,10,0,0,2,0,'Summon.pngThrow a structure that hits surrounding tiles when you Shuffle.pngShuffle. If you have Fragile.pngFragile, double its HP.','Let it rip!'),
    ('BlastCrystals','Blast Crystals',2,60,6,0,0,2,0,'Summon two Blast Crystals that fire a shot when destroyed.','POP POP!'),
    ('BlessingOfSusano','Blessing of Susano\'o',5,40,9,1,4,4,0,'Gain 100 Shield.pngShield and charge for 1 second to fire a huge laser. Anchor.pngAnchor. Consume.pngConsume.',
    'There\'s no better way to take out a hive of scum and villainy than a giant laser.'),
    ('StormBlizzard','Blizzard',5,20,1,1,48,4,0,'Slowly rain down shots that apply Frost.pngFrost.','Eventually, they\'ll freeze to death'),
    ('BlueBullets','Blue Bullets',1,0,6,1,20,2,0,'Shot dmg equals current Mana.pngMana.','flavor_text'),
    ('BombToss','Bomb Toss',2,150,6,0,0,2,0,'Throw a Bomb that explodes when destroyed.','Don\'t Fuze the hostage.'),
    ('Bombard','Bombard',1,200,6,0,0,2,0,'Hit and TileCrack.pngCrack 4 tiles away from each Structure','flavor_text'),
    ('Boomerang','Boomerang',3,50,2,0,0,1,0,'Throw a returning boomerang. Restore 2 Mana.pngMana on hit and Root.pngRoot targets for 2 seconds.',
    'Made in Australia'),
    ('BoosterShot','Booster Shot',1,0,8,0,0,2,0,'Shot Health-icon.pngHeals target for 100 HP. When this hits, fire a shot that applies 120 Poison.pngPoison.',
    'It\'s a matter of life and death.'),
    ('BladeThrow','Bouncing Blade',1,60,10,0,0,2,0,'Throw a blade, touch to throw again.','League of Saffron'),
    ('BowSnipe','Bow Snipe',4,250,7,0,0,3,0,'Charge and fire a piercing arrow. Anchor.pngAnchor.',
    'If I miss, it means I\'m just another dude with a bow'),
    ('Breakout','Breakout',1,120,7,0,0,2,0,'Hit surrounding tiles. Anchor.pngAnchor.','flavor_text'),
    ('Caltrops','Caltrops',2,30,7,0,0,2,0,'Throw spikes 4 tiles away that last 20 seconds. If you have Fragile.pngFragile, Relocation.pngteleport targets to random tiles.',
    'What are plastic bricks gonna do?'),
    ('Carpet Bomb','Carpet Bomb',3,120,1,1,8,3,0,'Hit a wide path with a 33% chance to leave Flame.pngFlames. Can hit self. Gain Fragile.pngFragile.',
    'Move or die.'),
    ('Castle','Castle',5,50,6,1,3,4,0,'Summon.pngSummon 3 Gun Turrets in a column in front. Consume.pngConsume.','Did you just summon a bunch of turrets in one turn?'),
    ('Cataclysm','Cataclysm',2,160,3,0,0,2,0,'Hit the edges of the enemy field and TileCrack.pngCrack. Increase next Shuffle.pngShuffle time by 2 seconds.',
    'flavor_text'),
    ('ChronoSphere','Chrono Sphere',1,30,3,0,0,5,0,'Fire a slow, piercing shot that Chrono.pngstops time when it hits a target.','flavor_text'),
    ('ClawTraps','Claw Traps',1,0,7,0,0,2,0,'Throw 2 traps that Root.pngRoot for 4 seconds.','flavor_text'),
    ('ColdMedicine','Cold Medicine',0,0,1,0,0,1,0,'Shot Health-icon.pngHeals target for 40 HP and applies 2 Frost.pngFrost.',
    'This\'ll help, trust me!'),
    ('ColdSnap','Cold Snap',1,0,1,0,0,2,0,'Apply Frost.pngFrost to all enemies.','Is it just me or is it cold in here?'),
    ('Coldstone','Coldstone',3,200,5,0,0,1,0,'Fire a rock. Flow.pngOn Flow, also cast Frostbolt.pngFrostbolt. gain 2 Flow.pngFlow.','flavor_text'),
    ('Combust','Combust',1,150,1,0,0,5,0,'Hit all Flame.pngFlames and refresh them.','Sparky Sparky Boom'),
    ('Corset','Corset',0,0,8,0,0,3,0,'Hit self for 40 dmg and gain 100 Shield.pngShield.','flavor_text'),
    ('CounterStrike','Counter Strike',2,0,9,0,0,2,0,'Fire 2 Kunai.pngKunai and gain 50 Shield.pngShield.','It protec but it also attac'),
    ('CrossturretToss','Cross Turret',2,150,6,0,0,3,0,'Throw a Cross Turret 4 tiles away.','flavor_text'),
    ('Crossfire','Crossfire',2,150,4,1,8,1,0,'Hit all tiles diagonal from you.','Don\'t get caught in this one'),
    ('Cryokinesis','Cryokinesis',2,100,1,0,0,2,0,'Charge a shot that applies 2 Frost.pngFrost.','Anima -- It\'s elementary.'),
    ('DeckShield','Deck Shield',2,0,9,0,0,1,0,'Gain 5 Shield.pngShield for each spell in your deck.','flavor_text'),
    ('DeckSlam','Deck Slam',2,10,3,0,0,2,0,'Shot deals 10 dmg for each spell in your deck.','flavor_text'),
    ('Detox','Detox',0,0,8,0,0,2,0,'Dmg everyone for double their Poison.pngPoison, remove their poison.',
    'Maple syrup, lemon juice, cayenne pepper and water'),
    ('Devour','Devour',3,80,8,0,0,3,0,'If this shot kills the target, Health-icon.pngHeal 100 HP. Consume.pngConsume.',
    'It\'s the circle of life'),
    ('DiagBeam','Diag Beam',2,20,9,1,5,2,0,'Fire a bouncing beam diagonally.','Simple geometry'),
    ('DiamondRing','Diamond Ring',1,40,9,0,0,3,0,'While in a cast slot, gain 4 Shield.pngShield every second.','flavor_text'),
    ('DoubleTap','Double Tap',4,120,8,1,2,3,0,'Fire two shots in quick succession. Execute.pngIf this kills an enemy, cast this again.',
    'Rule #2.'),
    ('MatKunais','Doubletake',1,0,10,0,0,1,0,'Add 2 Kunai.pngKunais to your deck.','Edible knives.'),
    ('Downfall','Downfall',2,2,9,0,0,5,0,'Hit in a 3x3 area 4 tiles away. Deals dmg equal to 2x your Shield.pngShield. Lose all Shield.pngShield.','flavor_text'),
    ('EarthPrayer','Earth Prayer',2,0,5,0,0,2,0,'On Flow, restore 4 Mana.pngMana. Gain 4 Flow.pngFlow.','flavor_text'),
    ('Earth Wyrm','Earth Wyrm',2,10,5,1,0,2,0,'Launch rocks that TileBreak.pngBreak 3 tiles away Channel.pnguntil you move. TileBreak.pngBreak the tile behind you.','flavor_text'),
    ('EarthenArmor','Earthen Armor',0,0,5,0,0,1,0,'Gain 40 Shield.pngShield and TileCrack.pngCrack adjacent tiles. Gain 2 Flow.pngFlow.','flavor_text'),
    ('Ember','Ember',0,10,1,0,0,2,0,'Create a Flame.pngFlame 4 tiles away.','A snap of the fingers.'),
    ('EmpowerRing','Empower Ring',1,40,2,0,0,3,0,'While in a cast slot, gain 5 SpellPower.pngSpell Power.','flavor_text'),
    ('Energizer','Energizer',2,90,4,0,0,2,0,'Energizer.png 	Fire a shot. Raise this spell\'s dmg by 30 for the rest of the battle.',
    'I\'m only getting stronger!'),
    ('Entangle','Entangle',1,20,5,0,0,2,0,'Root enemies in a large cone for 3 seconds.','flavor_text'),
    ('Entrench','Entrench',1,0,9,1,0,2,0,'Gain 80 Shield.pngShield and Root.pngRoot self for 2 sec. If you have Fragile.pngFragile, remove Root.pngRoot.',
    'Help, I\'m stuck.'),
    ('EternityCannon','Eternity Cannon',3,40,4,1,0,4,0,'Fires a shot every second. Flow.pngOn Flow, duplicate this spell. Consume.pngConsume. Gain 2 Flow.pngFlow.','flavor_text'),
    ('Excavate','Excavate',1,25,5,0,0,2,0,'Fire a missile from each TileBreak.pngBroken tile at the farthest enemy.','flavor_text'),
    ('Fadeaway','Fadeaway',2,250,7,0,0,2,0,'Teleport to the inverse tile and hit 4 tiles away.','Kobe!'),
    ('StormFire','Firestorm',4,30,1,1,12,3,0,'Rain down shots that leave Flame.pngFlames.','And fire rained from the sky'),
    ('Firewall','Firewall',2,40,1,0,0,1,0,'Create a column of Flame.pngFlames 4 tiles away.','flavor_text'),
    ('Fissure','Fissure',2,80,5,0,0,2,0,'Crack all tiles in front and Relocation.pngpush enemies aside. Gain 2 Flow.pngFlow.','Watch your step'),
    ('FlatEarth','Flat Earth',1,0,5,0,0,2,0,'Gain 10 Shield.pngShield for each TileBreak.pngBroken tile. Fix all TileBreak.pngBroken tiles.','Well the tiles are flat...'),
    ('Fling','Fling',1,0,3,0,0,3,0,'Cast the spell in the other slot and Backfire.pngBackfire.','flavor_text'),
    ('Flurry','Flurry',2,20,7,1,12,2,0,'Flurry.png 	Hits 3 tiles in front, and Relocation.pngpushes targets away.','ORA ORA ORA!'),
    ('Focus','Focus',1,0,2,0,0,2,0,'Gain 2 SpellPower.pngSpell Power.','I just really need to focus on my art right now.'),
    ('Forte','Forte',3,0,9,0,0,3,0,'Gain 150 Shield.pngShield. Consume.pngConsume.','...Gladly. Battle is my forte!'),
    ('Fracture','Fracture',2,120,5,0,0,1,0,'Fire a rock. Flow.pngOn Flow, cast this twice. Gain 2 Flow.pngFlow.','flavor_text'),
    ('FrostBarrage','Frost Barrage',2,40,1,1,3,1,0,'Fire shots that apply Frost.pngFrost in 3 rows.','Dodge this!'),
    ('Frostbolt','Frostbolt',1,40,1,0,0,1,0,'Fire a shot that applies Frost.pngFrost.','This spell isn\'t just cool, it\'s Ice Cool'),
    ('Glaive','Glaive',2,20,4,0,0,3,0,'Missile bounces between enemies.','flavor_text'),
    ('Glassify','Glassify',1,10,8,0,0,1,0,'Fire a shot that applies 3 Fragile.pngFragile.','They called me \'Mr. Glass\''),
    ('Glitterbomb','Glitterbomb',2,40,4,0,0,4,0,'Throw a cascading bomb that hits adjacent tiles 4 tiles away.','They\'ll be finding this stuff for weeks.'),
    ('StormGlitter','Glitterstorm',5,40,4,1,6,5,0,'Rain down shots that hit their adjacent tiles.','Glimmer -- Killing with style.'),
    ('Guillotine','Guillotine',3,80,10,0,0,4,0,'Hit a small column 4 tiles away. Execute targets with 300 HP or less.','As fearless in death as he was in life.'),
    ('SumTurretGun','Gun Turret',3,120,6,0,0,2,0,'Summon.pngSummon a Gun Turret.','Don\'t walk in front of this.'),
    ('StormIce','Hailstorm',4,20,1,1,18,3,0,'Rain down shots that apply Frost.pngFrost.','Rain or shine, but definitely not hail'),
    ('HealthCatch','Health Potion',1,0,8,0,0,3,0,'Catch this to Health-icon.pngHeal 40 HP. Consume.pngConsume.','Are you really playing catch with yourself?'),
    ('Hellfire','Hellfire',2,100,8,1,32,3,0,'Hit all tiles randomly, can hit self.','Like fire, hellfire, this fire in my skin'),
    ('HiredGun','Hired Gun',1,100,2,0,0,1,0,'Fire a shot. Lose 2 Money-icon.pngMoney. Execute.pngIf this kills an enemy, gain 4 Money-icon.pngMoney.','flavor_text'),
    ('HolyGround','Holy Ground',4,150,5,0,0,5,0,'Hit all enemies and TileCrack.pngCrack tiles, pushing enemies away. Gain 2 Flow.pngFlow.','flavor_text'),
    ('HyperBeam','Hyper Beam',3,50,7,1,4,4,0,'Fire a laser beam that Relocation.pngpushes yourself back. Reduce SpellPower.pngSpell Power by 2.',
    'TM15'),
    ('IceHockey','Ice Hockey',3,40,1,0,0,3,0,'Fire a bouncing beam diagonally that applies Frost.pngFrost.','flavor_text'),
    ('IceNeedle','Ice Needle',2,20,1,0,0,3,0,'Fire a piercing, returning shot, apply Frost.pngFrost on hit.','SHAA!'),
    ('IceSpikes','Ice Spikes',2,90,1,0,0,2,0,'Fire a trail of spikes that follows your movement and applies Frost.pngFrost.','Let it go'),
    ('Incline','Incline',3,40,2,0,0,2,0,'Create a shot on every tile in front.','flavor_text'),
    ('InfinityBeam','Infinity Beam',3,30,4,1,0,4,0,'Fire a laser beam Channel.pnguntil you move.','I\'ma firin mah LAZOR'),
    ('Innervate','Innervate',1,0,2,0,0,3,0,'Gain 1 MaxMana.pngMax Mana til end of battle. Add 1 Jam.pngJam to your deck.','If you have max mana, draw a spell.'),
    ('IonCannon','Ion Cannon',2,120,4,0,0,1,0,'Hit the 4 center tiles of the enemy field and TileCrack.pngCrack them.','Low orbit'),
    ('IronWill','Iron Will',0,200,9,0,0,3,0,'When this hits, give the target 180 Shield.pngShield.','flavor_text'),
    ('Jam','Jam',2,0,3,0,0,1,0,'Does nothing. Anchor.pngAnchor. Consume.pngConsume.','We got a real jam goin\' down'),
    ('JamCannon','Jam Cannon',0,80,3,1,0,2,0,'Fire a shot for every Jam.pngJam in your deck. Anchor.pngAnchor. Add 1 Jam.pngJam to your deck.',
    'And welcome to the jam'),
    ('JamSlam','Jam Slam',1,60,3,1,0,2,0,'Fire a shot 4 tiles away for every Jam.pngJam you cast this battle. Add 1 Jam.pngJam to your deck.','C\'mon and slam'),
    ('KineticWave','Kinetic Wave',2,40,7,1,4,1,0,'Hits 4 tiles in front, Relocation.pngpushing enemies away. Gain 2 Flow.pngFlow.','Hi! Bye!'),
    ('Knife','Knife',1,100,10,0,0,2,0,'Throw a fast knife. If you have Fragile.pngFragile duplicate this spell. Consume.pngConsume.','Don\'t bring this to a gunfight'),
    ('ForcePushDown','Knock Down',0,10,7,0,0,2,0,'Relocation.pngPush the target Down 1 tile.','flavor_text'),
    ('Kunai','Kunai',0,30,10,0,0,1,0,'Throw a knife up to 4 tiles away. Consume.pngConsume.','flavor_text'),
    ('SumTurretLaser','Laser Turret',3,120,6,0,0,3,0,'Summon a Laser Turret.','flavor_text'),
    ('Leech','Leech',2,40,8,0,0,2,0,'When this hits, Health-icon.pngHeal HP equal to this spell\'s dmg. Consume.pngConsume.','flavor_text'),
    ('LimitBreak','Limit Break',9,10,2,1,40,3,0,'Hit 4 tiles away. If you have Fragile.pngFragile, hit in a cross. Lose 1 MaxMana.pngMax Mana for 20 seconds. Mana.pngMana Cost is equal to your MaxMana.pngMax Mana.',
    'flavor_text'),
    ('MagicClaw','Magic Claw',2,60,10,1,2,1,0,'Hit in an X 4 tiles away, applies Fragile.pngFragile.','Min req - lvl 14 Magician'),
    ('ManaFusion','Mana Fusion',2,0,2,0,0,3,0,'Restore 5 Mana.pngMana.','Convergence -- One for all.'),
    ('ManaLattice','Mana Lattice',1,50,6,0,0,2,0,'Summon a Mana Crystal, drops 4 Mana.pngMana when destroyed.','I\'m saving it for later!'),
    ('ManaCatch','Mana Potion',0,0,2,0,0,1,0,'Catch this to restore 2 Mana.pngMana.','I\'m going into battle, and I need your strongest potions!'),
    ('ManaSteal','Mana Steal',3,120,2,0,0,1,0,'Regain Mana.pngMana Cost on hit. Gain 1 Trinity.pngTrinity. TrinityCast.pngIf Trinity is full, cast this twice.','flavor_text'),
    ('Meditate','Meditate',0,0,2,0,0,1,0,'Freeze for 0.5 seconds to restore 2 Mana.pngMana. Gain 1 Trinity.pngTrinity. Anchor.pngAnchor.','flavor_text'),
    ('Mine','Mine',2,250,6,0,0,3,0,'Plant a mine on a random enemy tile.','Mine? Mine? Mine?'),
    ('Minefield','Minefield',2,30,6,1,16,1,0,'Fill enemy field with mines','Not environmentally friendly'),
    ('ThunderLight','Mini Thunder',0,40,1,0,0,1,0,'Thunder hits 4 tiles away.','Shock and aww'),
    ('Minigun','Minnie Gun',1,5,6,1,12,1,0,'Fire 12 shots. Gain 1 Trinity.pngTrinity. TrinityCast.pngIf Trinity is full, cast this twice.',
    'This time, I\'ve got 12 shots.'),
    ('MissileTow','Missiletoe',2,40,5,1,3,2,0,'Fire missiles at the closest target. Root.pngRoot target for 1 second.','flavor_text'),
    ('SumMonument','Monument',2,250,6,0,0,4,0,'Summon a Monument that falls, summons blocks, and deals 250 dmg when destroyed','Hexawan -- Yes we can.'),
    ('Northwind','Northwind',3,100,7,1,4,3,0,'Fire shots from the top of the enemy field. Relocation.pngPush targets down and remove their Shield.pngShield.',
    'flavor_text'),
    ('OrbitalBeam','Orbital Beam',2,40,5,1,4,2,0,'Fire beams 4 tiles away that TileBreak.pngBreak tiles.','I\'ve got friends in high places'),
    ('Pandemic','Pandemic',2,0,8,0,0,3,0,'Poisoned targets explode, applying 60 Poison.pngPoison to themselves and nearby targets.','...let\'s move to Madagascar.'),
    ('PekayFire','Pekay Fire',1,30,1,0,0,1,0,'Fire a shot that leaves a Flame.pngFlame on hit.','Super hot faia'),
	('Pinch','Pinch',0,0,8,0,0,2,0,'Hit yourself for 1 dmg.','Wake me up inside (I can\'t wake up)'),
    ('Ping','Ping',1,30,2,0,0,3,0,'Fire a shot that bounces between you and the enemy.','Lagggggg'),
    ('PoisonDart','Poison Dart',1,20,8,0,0,1,0,'Fire a shot that applies 60 Poison.pngPoison.','Poison, the perfect weapon for a snake!'),
    ('PoisonTails','Poison Tails',1,40,8,1,4,2,0,'Hit the back row applying 80 Poison.pngPoison and pushing targets forward.','flavor_text'),
    ('PowerSaws','Power Saws',3,100,2,0,0,5,0,'Fire saws in adjacent rows that deal 100 dmg + 10 dmg per SpellPower.pngSpell Power.','flavor_text'),
    ('Preload','Preload',2,20,3,0,0,4,0,'Reduce next Shuffle.pngShuffle Time by 1 second.','Lock n\' load.'),
    ('Prophecy','Prophecy',2,240,5,0,0,3,0,'Hit a random row after 6 seconds, TileBreak.pngBreaks tiles, can hit self.','The end is coming.'),
    ('Pull','Pull',0,1,7,1,8,2,0,'Pull enemies closer to you. Anchor.pngAnchor.','Get over here.'),
    ('ForcePushUp','Push Up',0,10,7,0,0,2,0,'Push the target Up 1 tile.','flavor_text'),
    ('Pyroblast','Pyroblast',2,50,1,0,0,3,0,'Fire a shot that explodes on hit dealing 100 dmg','LETHAL'),
    ('Rage','Rage',2,30,1,0,0,3,0,'Hit in a cross 4 tiles away. Deals 30 extra dmg for each Flame.pngFlame','Release that witch!'),
    ('Ragnarok','Ragnarok',4,350,10,0,0,4,0,'Summon a giant sword that TileBreak.pngBreaks 4 tiles away.','See u at VA-11 Hall-A'),
    ('LaserTriple','Railgun',0,50,3,1,3,2,0,'Fire piercing lasers. Add 2 Jam.pngJam to your deck.','flavor_text'),
    ('Reflector','Reflector',1,0,9,0,0,2,0,'Gain 5 Reflect.pngReflect for 0.6 seconds.','Don\'t forget to jump cancel'),
    ('Rest','Rest',2,0,8,0,0,2,0,'Freeze for 1 second to Health-icon.pngHeal 40 HP. Anchor.pngAnchor. Consume.pngConsume.','For when you\'re feeling Hollow.'),
    ('Revenge','Revenge',1,100,8,0,0,1,0,'Hit the last target that hit you.','Come on, HIT ME!'),
    ('RingOfFire','Ring Of Fire',3,20,1,0,0,2,0,'Create a circle of Flame.pngFlames 4 tiles away','I went down, down, down, and the flames went higher.'),
    ('River','River',3,40,7,1,0,1,0,'Fire Relocation.pngpushing shots in adjacent rows Channel.pnguntil you move. Gain 1 Flow.pngFlow on hit.','flavor_text'),
    ('RockCycle','Rock Cycle',1,60,5,0,0,1,0,'On Flow, return this to your deck. Anchor.','flavor_text'),
    ('SapphireRing','Sapphire Ring',1,40,2,0,0,3,0,'While in a cast slot, gain 3 Max Mana.','flavor_text'),
    ('Sequencer','Sequencer',2,0,2,0,0,2,0,'Catch to fire an 80 dmg shot and gain Trinity.pngTrinity, three times.','Sequencer'),
    ('ShardToss','Shard Toss',1,50,6,1,2,1,0,'Summon two Shards on random enemy tiles that explode for 50 dmg after 2.5 seconds','What is that mysterious ticking noise?'),
    ('Shattersaw','Shattersaw',2,20,4,0,0,1,0,'Shot shatters on hit and dealing 60 dmg to 3 enemies.','flavor_text'),
    ('ShieldBeam','Shield Beam',2,20,9,1,2,2,0,'When this hits, gain 20 Shield.pngShield. Anchor.pngAnchor.','It attac but it also protec'),
    ('ShieldCatch','Shield Catch',1,0,9,0,0,1,0,'Catch this to gain 60 Shield.pngShield.','This is how I eat popcorn.'),
    ('ShieldThrow','Shield Throw',1,0,9,0,0,2,0,'Fire a shot that deals dmg equal to your Shield.pngShield. Lose all Shield.pngShield. Catch to regain Shield.pngShield.','When you have no sword and no options'),
    ('SumShieldgen','Shieldgen',2,80,6,0,0,2,0,'Summon a Shield Generator that gives 10 Shield.pngShield every second.','flavor_text'),
    ('ShieldsUp','Shields Up',1,0,9,0,0,1,0,'Gain 40 Shield','Phalanx -- The best defense is a good defense'),
    ('Shine','Shine',3,30,4,1,8,3,0,'Converge shots from a circle 4 tiles away.','Everything\'s shiny, captain!'),
    ('Shotgun','Shotgun',2,100,6,1,3,1,0,'Hit enemies in a small cone, hits 3 times on the first tile','Point this at something you don\'t like'),
    ('Showdown','Showdown',0,0,8,0,0,2,0,'Everyone gains Fragile.pngFragile.','flavor_text'),
    ('LaserSolo','Skewer',0,60,3,0,0,1,0,'Fire a piercing laser. Add 1 Jam.pngJam to your deck.','flavor_text'),
    ('SludgeBomb','Sludge Bomb',3,20,8,1,8,2,0,'Fire 8 missiles 4 tiles away that apply 20 Poison.pngPoison.','flavor_text'),
    ('Smog','Smog',3,0,8,1,18,3,0,'Fire 3 waves of 6 shots on random enemy tiles that apply 60 Poison.pngPoison.','flavor_text'),
    ('SolarBeam','Solar Beam',3,200,4,0,0,4,0,'Fire a powerful wide laser','flavor_text'),
    ('SolarCharge','Solar Charge',3,0,4,0,0,4,0,'Freeze for 0.5 seconds and add 1 SolarBeam.pngSolar Beam to your deck. Anchor.pngAnchor.','Praise the sun.'),
    ('SoulLink','Soul Link',1,0,8,0,0,2,0,'Shot applies Link.pngLink for 6 seconds.','flavor_text'),
    ('SpiritSword','Spirit Sword',3,30,4,0,0,4,0,'Hit 5 tiles in front of you for a short duration.','flavor_text'),
    ('SteelSkin','Steel Skin',1,0,9,0,0,3,0,'Gain 40 Defense for 3 seconds.','flavor_text'),
    ('StepPierce','Step Pierce',2,120,10,0,0,2,0,'Dash fwd, hitting 4 tiles, removes Shield.pngShield from targets. Anchor.pngAnchor.',
    'When You were partying I studied The Blade'),
    ('StepSlash','Step Slash',2,80,10,0,0,2,0,'Dash fwd and hit enemies in front. Anchor.pngAnchor.','Some say you can dodge lasers.'),
    ('SuperMiniGun','Super Minnie Gun',4,2,6,1,100,4,0,'SuperMinigun.png 	Fire 100 shots. Consume.pngConsume.','Spray and pray.'),
    ('Sustain','Sustain',1,0,3,0,0,4,0,'Gain 1 Trinity.pngTrinity. TrinityCast.pngIf Trinity is full, gain Shield.pngShield equal to dmg of spell in other slot.','flavor_text'),
    ('Sweeper','Sweeper',2,60,6,1,16,2,0,'Hit all enemy tiles in a sweeping pattern','Line em up, knock em down.'),
    ('Swipe','Swipe',1,40,10,0,0,1,0,'Hit 5 tiles in front, add 1 Kunai.pngKunai to your deck on hit.','Everyone\'s carrying knives these days...'),
    ('Switchbait','Switchbait',2,0,3,0,0,3,0,'Shot deals dmg of spell in other slot.','Doublelift -- A sleight advantage.'),
    ('SwordLine','Sword Row',2,20,5,0,0,1,0,'Swords fall in front and Root.pngRoot for 3 seconds.','flavor_text'),
    ('StormSword','Swords of Light',2,20,5,1,6,3,0,'StormSword.png 	Rain down swords that Root.pngRoot for 3 seconds.','A storm of swords.'),
    ('Thunder','Thunder',1,100,1,0,0,1,0,'Thunder hits 4 tiles away','Shock and awe'),
    ('StormThunder','Thunderstorm',4,80,1,1,24,2,0,'Rain down thunderstrikes','flavor_text'),
    ('TileFire','Tile Fire',2,120,5,1,2,1,0,'Break and throw tiles above and below. Gain 2 Flow.pngFlow.','Hearth -- Some things are meant to be broken.'),
    ('TimeSlow','Time Slow',1,0,3,0,0,3,0,'Slows time for 3 seconds.','flavor_text'),
    ('TractorBeam','Tractor Beam',1,5,7,1,0,2,0,'Beam Relocation.pngpulls enemies towards you Channel.pnguntil you move.',
    'You\'re mine now.'),
    ('Transfuse','Transfuse',0,0,8,0,0,2,0,'Hit self for 5 dmg, restore 2 Mana.pngMana.','I hate needles'),
    ('Tremor','Tremor',1,140,5,0,0,1,0,'Fire a rock and TileCrack.pngCrack adjacent tiles. Flow.pngOn Flow, fix adjacent tiles. Gain 2 Flow.pngFlow.','flavor_text'),
    ('TriRag','Tri Rag',1,40,2,0,0,2,0,'Gain 1 Trinity.pngTrinity. TrinityCast.pngIf Trinity is full, cast Ragnarok.pngRagnarok.','flavor_text'),
    ('TriShot','Tri Shot',3,60,2,1,3,1,0,'Hits three ways. Gain 1 Trinity.pngTrinity. TrinityCast.pngIf Trinity is full, cast thrice.',
    'Oh baby a triple!'),
    ('Trisect','Trisect',2,33,3,0,0,4,0,'Fire a laser beam. TrinityCast.pngIf Trinity is full, deal dmg equal to 1/3 of target\'s HP. Gain 1 Trinity.pngTrinity. Add 1 Jam.pngJam to your deck.','flavor_text'),
    ('Tsunami','Tsunami',3,50,7,1,12,3,0,'Push back enemies in first three columns. Gain 2 Flow.pngFlow.','Kinesys -- Unstoppable force.'),
    ('SumTurretSD','Turret SD',2,100,6,0,0,3,0,'Summon a Self Defense Turret. Consume.pngConsume.','flavor_text'),
    ('Twinferno','Twinferno',2,60,1,0,0,2,0,'Explosions on every other tile in front','Boom boom'),
    ('Undertow','Undertow',2,40,7,1,8,1,0,'Pull back half of enemy field. Gain 2 Flow.pngFlow.','flavor_text'),
    ('Upwind','Upwind',2,50,7,0,0,1,0,'Wide piercing shot, Relocation.pngpushes targets up.','flavor_text'),
    ('Viruspell','Viruspell',0,20,3,0,0,3,0,'Fire a shot and duplicate this spell. Anchor.pngAnchor.','I\'ve got speeells, they\'re multiplyin.'),
    ('Volley','Volley',1,100,6,0,0,1,0,'Fire a shot from each Structure','On my command!'),
    ('Wall','Wall',0,60,6,0,0,2,0,'Summon a Wall','Just build lol'),
    ('WarpRays','Warp Rays',2,40,7,1,8,3,0,'Hit adjacent rows, Relocation.pngteleport targets to random tiles.','Beam \'em up, Scotty'),
    ('Warpath','Warpath',5,120,10,0,0,5,0,'Slash every tile in front. If you have Fragile.pngFragile, Relocation.pngteleport targets in front of you. Anchor.pngAnchor.',
    'You are already dead.'),
    ('Waterfall','Waterfall',2,40,5,1,0,5,0,'Fire a shot 4 tiles away for every Flow.pngFlow stack. Gain 1 Flow.pngFlow on hit.','flavor_text'),
    ('Whirl','Whirl',2,30,2,1,6,2,0,'Hits 3 tiles in front. Anchor.pngAnchor.','Don\'t breathe this.'),
    ('Wildfire','Wildfire',3,40,1,1,5,3,0,'Fire 5 shots from random tiles that leave a Flame.pngFlame on hit','I\'m too cool to aim'),
    ('Wobble','Wobble',2,30,7,1,4,2,0,'Hit enemies Relocation.pngback and forth 2 tiles in front.','Why isn\'t this banned?'),
    ('Wreath','Wreath',1,0,5,0,0,2,0,'Root enemies for 3 seconds in a circle 4 tiles away.','Stop squirming!'),
    ('Yami','Yami',0,9999,11,1,10,6,0,'Fire 10 dark shots. Anchor.pngAnchor.','flavor_text'),
    ('Zenith','Zenith',0,150,4,0,0,2,0,'Delayed 3x3 explosion on current tile, can hit self.','Use right before dashing!'),
    ('ZigZag','ZigZag',2,10,4,1,7,1,0,'Fire a zig zagging shot.','I think you zigged when you should\'ve zagged.'),
    -- unlisted levels on wiki for next entry blob
    ('Jackhammer','Jackhammer',2,150,5,1,0,4,0,'Hit all TileCrack.pngCracked tiles 3 times and TileBreak.pngBreak them.','flavor_text'),
    ('JamShield','Jam Shield',0,0,9,0,0,1,0,'Gain 50 Shield.pngShield. Add 1 Jam.pngJam to your deck.','flavor_text'),
    ('Meltdown','Meltdown',1,60,1,0,0,1,0,'Hit all enemies with Frost.pngFrost and leave a Flame.pngFlame on hit.','flavor_text'),
    ('Paragon','Paragon',2,120,4,1,4,2,0,'Hit in a diamond 4 tiles away.','flavor_text'),
    ('Ramjet','Ramjet',1,120,3,0,0,1,0,'Fire a homing missile that TileCrack.pngCracks a tile. Increase next Shuffle.pngShuffle time by 2 seconds.','flavor_text'),
    ('StormSaw','Sawstorm',5,40,4,1,48,5,0,'Rain down shattersaws on random enemy tiles','flavor_text'),
    ('ShadowShift','Shadow Shift',2,0,10,0,0,1,0,'Fire 3 Kunai.pngKunai and teleport to the inverse tile.','flavor_text'),
    ('SumSilomini','Silo',5,300,6,0,0,5,0,'Summon a structure that explodes a missile after 12 seconds.','flavor_text'),
    ('Sleight','Sleight',1,0,3,0,0,1,0,'Trigger Shuffle.pngShuffle artifacts.','flavor_text'),
    ('Slice','Slice',0,80,10,0,0,1,0,'Hit column in front, Apply 40 Poison.pngPoison','flavor_text'),
    ('SpikeStrip','Spike Strip',1,30,7,0,0,2,0,'Throw spikes on all tiles in front that lasts 20 seconds.','flavor_text'),
    ('SumSunbeamer','Sunbeamer',2,120,6,0,0,2,0,'Summon a structure that fires a beam of light 4 tiles away.','flavor_text'),
    ('Sunder','Sunder',2,150,1,0,0,4,0,'Strike all enemies with Frost.pngFrost, apply 1 Fragile.pngFragile.','flavor_text'),
    -- end of blob
    ('Explosion','EXPLOSION!',5,666,1,0,0,5,1,'text','flavor_text'),
    ('SeraCannon','Sera Cannon',2,0,2,0,0,4,1,'text','flavor_text'),
    ('Salamander','Salamander',2,40,1,0,0,2,2,'text','flavor_text'),
    ('BackBurner','Back Burner',1,60,1,0,0,2,3,'text','flavor_text'),
    ('Flamberge','Flamberge',2,30,1,0,0,4,3,'text','flavor_text'),
    ('Brushfire','Brushfire',1,0,1,0,0,2,4,'text','flavor_text'),
    ('Frostbite','Frostbite',0,0,1,0,0,2,5,'text','flavor_text'),
    ('Fimbulveter','Fimbulveter',4,0,1,1,6,5,6,'text','flavor_text'),
    ('IceShield','Ice Shield',2,0,9,0,0,4,6,'text','flavor_text'),
    ('MissMeShield','Miss-Me Shield',1,0,9,0,0,2,8,'text','flavor_text'),
    ('FateShield','Fate Shield',1,0,9,0,0,2,9,'text','flavor_text'),
    ('BloodShield','Blood Shield',1,0,8,1,0,4,10,'text','flavor_text'),
    ('Scavenge','Scavenge',2,0,10,0,0,5,12,'text','flavor_text'),
    ('CollectRing','Collect Ring',1,40,10,0,0,3,13,'text','flavor_text'),
    ('Monsoon','Monsoon',4,20,7,1,30,5,15,'text','flavor_text'),
    ('Venoshock','Venoshock',2,0,8,0,0,3,15,'text','flavor_text'),
    ('Backstab','Backstab',2,40,8,1,4,2,16,'text','flavor_text'),
    ('Twoxin','Twoxin',2,0,8,0,0,2,17,'text','flavor_text'),
    ('Sidewinder','Sidewinder',2,50,6,1,0,3,20,'text','flavor_text'),
    ('Amalgam','Amalgam',2,10,2,0,0,3,21,'text','flavor_text'),
    ('Echo','Echo',2,0,3,0,0,3,22,'text','flavor_text'),
    ('FlintShot','Flint Shot',2,200,5,0,0,2,23,'text','flavor_text'),
    ('BladeRain','Blade Rain',2,0,10,0,0,3,24,'text','flavor_text'),
    ('Bladeskrieg','Bladeskrieg',4,0,10,0,0,5,24,'text','flavor_text'),
    ('ChargeRing','Charge Ring',1,40,2,0,0,3,25,'text','flavor_text'),
    ('Excalibur','Excalibur',3,0,10,0,0,5,25,'text','flavor_text'),
    ('BeamCrystals','Beam Crystals',2,60,6,1,2,2,26,'text','flavor_text'),
    ('SumGrail','Grail',2,1,6,0,0,4,26,'text','flavor_text'),
    ('Circuit','Circuit',1,40,4,0,0,3,27,'text','flavor_text'),
    ('Cynet','Cynet',3,0,8,0,0,5,28,'text','flavor_text'),
    ('LastLetter','Last Letter',3,100,10,0,0,3,28,'text','flavor_text'),
    ('StepFury','Fury',3,NULL,10,0,0,5,29,'text','flavor_text'),
    ('LifeSword','Lifesword',2,400,10,0,0,5,29,'text','flavor_text'),
    ('Resonate','Resonate',1,50,6,0,0,3,30,'text','flavor_text'),
    ('RockTomb','Rock Tomb',4,100,5,1,4,3,30,'text','flavor_text'),
    ('SpellShield','Spell Shield',2,0,9,0,0,3,31,'text','flavor_text'),
    ('Stasis','Stasis',2,0,9,0,0,4,31,'text','flavor_text'),
    ('Salvage','Salvage',1,0,6,0,0,2,32,'text','flavor_text'),
    ('SoulFire','Soul Fire',2,60,4,0,0,2,32,'text','flavor_text'),
    ('Skipper','Skipper',2,120,7,0,0,3,36,'text','flavor_text'),
    ('TriForce','Tri Force',0,0,2,0,0,4,36,'text','flavor_text'),
    ('Sunshine','Sunshine',4,2,4,1,50,5,37,'text','flavor_text'),
    ('TimeStop','Time Stop',2,0,3,0,0,4,37,'text','flavor_text'),
    ('Gambit','Gambit',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Blink','Blink',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('AmbientBurst','Ambient Burst',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Unleash','Unleash',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Vivisection','vivisection',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Midnight','Midnight',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('WeedWacker','Weed Wacker',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Wonder','Wonder',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Inverter','Inverter',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Overload','Overload',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Haven','Haven',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Salvo','Salvo',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text'),
    ('Stinger','Stinger',cost,damage,brand,s_repeat,repititions,rarity,lvl_obtained,'text','flavor_text')
    ;
    
	/*
    No Unlock level listed on the fandom site. Assumed 0, but keeping this here in case they aren't lol
    ('Jackhammer','Jackhammer',2,150,5,1,0,4,lvl_obtained,'Hit all TileCrack.pngCracked tiles 3 times and TileBreak.pngBreak them.','flavor_text'),
    ('JamShield','Jam Shield',0,0,9,0,0,1,lvl_obtained,'Gain 50 Shield.pngShield. Add 1 Jam.pngJam to your deck.','flavor_text'),
    ('Meltdown','Meltdown',1,60,1,0,0,1,lvl_obtained,'Hit all enemies with Frost.pngFrost and leave a Flame.pngFlame on hit.','flavor_text'),
    ('Paragon','Paragon',2,120,4,1,4,2,lvl_obtained,'Hit in a diamond 4 tiles away.','flavor_text'),
    ('Ramjet','Ramjet',1,120,3,0,0,1,lvl_obtained,'Fire a homing missile that TileCrack.pngCracks a tile. Increase next Shuffle.pngShuffle time by 2 seconds.','flavor_text'),
    ('StormSaw','Sawstorm',5,40,4,1,48,5,lvl_obtained,'Rain down shattersaws on random enemy tiles','flavor_text'),
    ('ShadowShift','Shadow Shift',2,0,10,0,0,1,lvl_obtained,'Fire 3 Kunai.pngKunai and teleport to the inverse tile.','flavor_text'),
    ('SumSilomini','Silo',5,300,6,0,0,5,lvl_obtained,'Summon a structure that explodes a missile after 12 seconds.','flavor_text'),
    ('Sleight','Sleight',1,0,3,0,0,1,lvl_obtained,'Trigger Shuffle.pngShuffle artifacts.','flavor_text'),
    ('Slice','Slice',0,80,10,0,0,1,lvl_obtained,'Hit column in front, Apply 40 Poison.pngPoison','flavor_text'),
    ('SpikeStrip','Spike Strip',1,30,7,0,0,2,lvl_obtained,'Throw spikes on all tiles in front that lasts 20 seconds.','flavor_text'),
    ('SumSunbeamer','Sunbeamer',2,120,6,0,0,2,lvl_obtained,'Summon a structure that fires a beam of light 4 tiles away.','flavor_text'),
    ('Sunder','Sunder',2,150,1,0,0,4,lvl_obtained,'Strike all enemies with Frost.pngFrost, apply 1 Fragile.pngFragile.','flavor_text'),
    */
