/*
('id','name',rarity,unlock_level,'text','flavor_text')
ordered by level obtained on https://onestepfromeden.fandom.com/wiki/Artifacts
*/
INSERT INTO osfe_spells
VALUES 
    ('Bulwark ','Bulwark ',2,0,'Start battles with 40 Shield.pngShield.','It\'s free shield estate.'),
    ('Citrine','Citrine',1,0,'Restore 0.2 Mana.pngMana when Flame.pngFlame dmg is dealt.','flavor_text'),
    ('CoverFire','Cover Fire',3,0,'Gain 5 AtkDmg.pngAttack Damage while Shuffle.pngShuffling.','I\'m going in, cover me!'),
    ('HeartOfTheCards','Heart of the Cards',1,0,'Health-icon.pngHeal HP equal to the number of Spells in your deck at the start of battle.','It\'s free heal estate'),
    ('Moonstone','Moonstone',1,0,'Gain 0.2 ManaRegen.pngMana Regen for each TileBreak.pngBroken tile.','flavor_text'),
    ('SubTank','Second Soul',4,0,'On Death, Health-icon.pngHeal 600 HP. Only works once.','Let\'s do that again.'),
    ('PetDragon','Pet Dragon',4,2,'A dragon that shoots fireballs that leave Flame.pngFlames when you cast a spell.','flavor_text'),
    ('MoltenCore','Molten Core',3,4,'Gain 3 Shield.pngShield whenever Flame.pngFlame dmg is dealt.','flavor_text'),
    ('Frostmail','Frostmail',4,5,'Fire a Frostbolt.pngFrostbolt when you get hit. Lose 10 SpellPower.pngSpell Power.','Revenge is a dish best served Cold.'),
    ('Icing','Icing',3,7,'Fire a Frostbolt.pngFrostbolt when you cast Jam.pngJam.','flavor_text'),
    ('SnowBoots','Snow Boots',1,7,'When Frost.pngFrost dmg is dealt also Root.pngRoot the target for 2 seconds.','flavor_text'),
    ('ColdPressedJuice','Cold Pressed Juice',3,8,'Health-icon.pngHeal 20 HP when Frost.pngFrost dmg is dealt.','Overpriced but delicious'),
    ('HardenedShields','Hardened Shields',2,9,'Defense.pngDefense also reduces Shield.pngShield dmg.','flavor_text'),
    ('Acupuncture','Acupuncture',2,10,'Kunai.pngKunais apply Fragile.pngFragile.','flavor_text'),
    ('GripTape','Grip Tape',3,11,'Kunais cost 1 Mana.pngMana but deal double damage','flavor_text'),
    ('MasonJar','Masonjar',3,11,'Apply Fragile.pngFragile to everyone whenever you go below 1 Mana.pngMana.','flavor_text'),
    ('CassidyScarf','Cassidy\'s Scarf',2,12,'Chrono.pngStop time for 5 seconds when you go below 200 HP.','Anything\'s possible in a dream.'),
    ('Ninjutsu','Ninjutsu',4,13,'50% Chance to add a Kunai.pngKunai to your deck when you hit a target with a Kunai.pngKunai.','flavor_text'),
    ('ImmuneSystem','Immune System',3,14,'Gain 20 Shield.pngShield whenever Poison.pngPoison dmg is dealt.','flavor_text'),
    ('ShadowToxin','Shadow Toxin',3,14,'Kunai.pngKunais apply 20 Poison.pngPoison.','flavor_text'),
    ('ResistantStrain','Resistant Strain',2,16,'Poison.pngPoison never drops below 20, including on yourself.','I\'ll wait.'),
    ('ChaosFrag','Chaos Fragment',2,17,'Gain random effects at the start of battle.','Seems a bit buggy.'),
    ('DartFrog','Dart Frog',4,18,'Apply 4 Poison.pngPoison when a spell hits an enemy.','Jerro jerro'),
    ('Thorn','Thorn',4,18,'Gain 3 SpellPower.pngSpell Power, but Shield.pngShield decays slowly.','How irregular'),
    ('UnicornBomb','Unicorn Bomb',4,19,'Hit enemies with 40 dmg rainbows that remove a buff at the start of battle.','Don\'t believe unicorns are real.'),
    ('Vaccine','Vaccine',2,19,'Health-icon.pngHeal 160 HP and gain 80 Poison.pngPoison at the start of battle.','flavor_text'),
    ('Flechette','Flechette',2,20,'Weapon hits ricochet and hit another enemy.','flavor_text'),
    ('PetKitty','Pet Kitty',4,21,'A kitty that fires Frost.pngFrost shots three ways when you cast a spell.','flavor_text'),
    ('PocketSand','Pocket Sand',3,22,'Gain Invincible.pnginvincibility for 1 second when you Shuffle.pngShuffle.','Shuffle to dodge.'),
    ('PhasePlates','Phase Plates',4,23,'text','flavor_text'),
    ('Daffodil','Daffodil',3,33,'text','flavor_text'),
    ('Lilac','Lilac',4,33,'text','flavor_text'),
    ('SpellthiefLicense','Spellthief License',3,34,'text','flavor_text'),
    ('Stoplight','Stoplight',1,35,'text','flavor_text'),
    ('Tessellate','Tessellate',1,35,'text','flavor_text'),
    ('CandyWrapper','Candy Wrapper',2,38,'text','flavor_text'),
    ('Mother','Mother',4,39,'text','flavor_text'),
    ('Trifrost','Trifrost',3,39,'text','flavor_text'),
    ('DuelDisk','Duel Disk',4,40,'text','flavor_text'),
    ('Goldfish','Goldfish',3,40,'text','flavor_text'),
    ('PetFox','Pet Fox',3,41,'text','flavor_text'),
    ('Transcendence','Transcendence',4,42,'text','flavor_text'),
/* no levels entered in below blob */
    ('ThreeDPrinter','3D Printer',1,unlock_level,'text','flavor_text'),
    ('AdaptiveArmor','Adaptive Armor',1,unlock_level,'text','flavor_text'),
    ('Adrenaline','Adrenaline',2,unlock_level,'text','flavor_text'),
    ('Aether','Aether',3,unlock_level,'text','flavor_text'),
    ('Amethyst','Amethyst',2,unlock_level,'text','flavor_text'),
    ('Anthrax','Anthrax',3,unlock_level,'text','flavor_text'),
    ('Anvil','Anvil',1,unlock_level,'text','flavor_text'),
    ('Bandage','Bandage',2,unlock_level,'text','flavor_text'),
    ('BazsWhip','Baz\'s Whip',4,unlock_level,'text','flavor_text'),
    ('Beaker','Beaker',2,unlock_level,'text','flavor_text'),
    ('Beret','Beret',4,unlock_level,'text','flavor_text'),
    ('Bismuth','Bismuth',2,unlock_level,'text','flavor_text'),
    ('BlazeOfGlory','Blaze Of Glory',1,unlock_level,'text','flavor_text'),
    ('BloodMoney','Blood Money',3,unlock_level,'text','flavor_text'),
    ('BlueBlood','Blue Blood',1,unlock_level,'text','flavor_text'),
    ('BlueFlame','Blue Flame',2,unlock_level,'text','flavor_text'),
    ('BlueberryJam','Blueberry Jam',2,unlock_level,'text','flavor_text'),
    ('BoltAction','Bolt Action',1,unlock_level,'text','flavor_text'),
    ('Bubble','Bubble',1,unlock_level,'text','flavor_text'),
    ('CardThrower','Card Thrower',2,unlock_level,'text','flavor_text'),
    ('CensorBar','Censor Bar',1,unlock_level,'text','flavor_text'),
    ('Chalice','Chalice',3,unlock_level,'text','flavor_text'),
    ('ChocoMintChip','Choco Mint Chip',1,unlock_level,'text','flavor_text'),
    ('CobraCare','Cobra Care',2,unlock_level,'text','flavor_text'),
    ('ColdBlooded','Cold Blooded',2,unlock_level,'text','flavor_text'),
    ('CoolShoes','Cool Shoes',4,unlock_level,'text','flavor_text'),
    ('CreditCard','Credit Card',2,unlock_level,'text','flavor_text'),
    ('Cryophage','Cryophage',1,unlock_level,'text','flavor_text'),
    ('Curacao','Curacao',1,unlock_level,'text','flavor_text'),
    ('Delta','Delta',1,unlock_level,'text','flavor_text'),
    ('DoubleEdge','Double Edge',2,unlock_level,'text','flavor_text'),
    ('DoubleMint','Double Mint',4,unlock_level,'text','flavor_text'),
    ('DuctTape','Duct Tape',2,unlock_level,'text','flavor_text'),
    ('Elysium','Elysium',3,unlock_level,'text','flavor_text'),
    ('EmptyBottle','Empty Bottle',1,unlock_level,'text','flavor_text'),
    ('Eschaton','Eschaton',4,unlock_level,'text','flavor_text'),
    ('ExplosiveTendons','Explosive Tendons',1,unlock_level,'text','flavor_text'),
    ('Feather','Feather',2,unlock_level,'text','flavor_text'),
    ('FlakJacket','Flak Jacket',3,unlock_level,'text','flavor_text'),
    ('FlashLoader','Flash Loader',3,unlock_level,'text','flavor_text'),
    ('Fragment','Fragment',3,unlock_level,'text','flavor_text'),
    ('FreezerBurn','Freezer Burn',4,unlock_level,'text','flavor_text'),
    ('Gelatin','Gelatin',2,unlock_level,'text','flavor_text'),
    ('GhostCostume','Ghost Costume',3,unlock_level,'text','flavor_text'),
    ('GiantArmor','Giant Armor',3,unlock_level,'text','flavor_text'),
    ('GlassCannon','Glass Cannon',1,unlock_level,'text','flavor_text'),
    ('Champagne','Glass Flute',2,unlock_level,'text','flavor_text'),
    ('GoldenCat','Golden Cat',2,unlock_level,'text','flavor_text'),
    ('Granite','Granite',2,unlock_level,'text','flavor_text'),
    ('Harpoon','Harpoon',1,unlock_level,'text','flavor_text'),
    ('HeartOfGold','Heart of Gold',4,unlock_level,'text','flavor_text'),
    ('HexBadge','Hex Badge',3,unlock_level,'text','flavor_text'),
    ('HitSeeker','Hit Seeker',1,unlock_level,'text','flavor_text'),
    ('HoningSteel','Honing Steel',2,unlock_level,'text','flavor_text'),
    ('IceFloe','Ice Floe',1,unlock_level,'text','flavor_text'),
    ('IceSculpture','Ice Sculpture',1,unlock_level,'text','flavor_text'),
    ('Kabob','Kabob',1,unlock_level,'text','flavor_text'),
    ('KineticShield','Kinetic Shield',2,unlock_level,'text','flavor_text'),
    ('KnifeBelt','Knife Belt',1,unlock_level,'text','flavor_text'),
    ('LaserPointer','Laser Pointer',2,unlock_level,'text','flavor_text'),
    ('LifeJacket','Life Jacket',1,unlock_level,'text','flavor_text'),
    ('Lily','Lily',3,unlock_level,'text','flavor_text'),
    ('LinkCable','Link Cable',3,unlock_level,'text','flavor_text'),
    ('LongSleeves','Long Sleeves',3,unlock_level,'text','flavor_text'),
    ('LuckBox','Luck Box',2,unlock_level,'text','flavor_text'),
    ('LuckyCoin','Lucky Coin',3,unlock_level,'text','flavor_text'),
    ('Luna','Luna',3,unlock_level,'text','flavor_text'),
    ('GunnerFrontAll','M1 Liofire (Artifact)',2,unlock_level,'text','flavor_text'),
    ('GunnerHoming','M2 Hunter Seeker (Artifact)',2,unlock_level,'text','flavor_text'),
    ('MagnifyingGlass','Magnifying Glass',2,unlock_level,'text','flavor_text'),
    ('ManaGem','Mana Gem',2,unlock_level,'text','flavor_text'),
    ('ManaVein','Mana Vein',1,unlock_level,'text','flavor_text'),
    ('ManaJam','Manajam',1,unlock_level,'text','flavor_text'),
    ('MeatShield','Meat Shield',3,unlock_level,'text','flavor_text'),
    ('Medkit','Medkit',3,unlock_level,'text','flavor_text'),
    ('MeritBadge','Merit Badge',4,unlock_level,'text','flavor_text'),
    ('MicroMissiles','Micro Missiles',1,unlock_level,'text','flavor_text'),
    ('MiningRig','Mining Rig',2,unlock_level,'text','flavor_text'),
    ('MintTea','Mint Tea',1,unlock_level,'text','flavor_text'),
    ('Miracle','Miracle',3,unlock_level,'text','flavor_text'),
    ('Mirror','Mirror',4,unlock_level,'text','flavor_text'),
    ('Mitosis','Mitosis',2,unlock_level,'text','flavor_text'),
    ('Mjolnir','Mjolnir',4,unlock_level,'text','flavor_text'),
    ('Monocle','Monocle',1,unlock_level,'text','flavor_text'),
    ('Multitool','Multitool',1,unlock_level,'text','flavor_text'),
    ('MuzzleBrake','Muzzle Brake',1,unlock_level,'text','flavor_text'),
    ('NerveGas','Nerve Gas',1,unlock_level,'text','flavor_text'),
    ('PantherHabit','Panther Habit',2,unlock_level,'text','flavor_text'),
    ('PaperWallet','Paper Wallet',2,unlock_level,'text','flavor_text'),
    ('Pendulum','Pendulum',1,unlock_level,'text','flavor_text'),
    ('PetLiger','Pet Liger',4,unlock_level,'text','flavor_text'),
    ('PetPuppy','Pet Puppy',3,unlock_level,'text','flavor_text'),
    ('PetTurtle','Pet Turtle',3,unlock_level,'text','flavor_text'),
    ('PiggyBank','Piggy Bank',2,unlock_level,'text','flavor_text'),
    ('Pinwheel','Pinwheel',1,unlock_level,'text','flavor_text'),
    ('PocketWatch','Pocket Watch',3,unlock_level,'text','flavor_text'),
    ('PoisonVial','Poison Vial',1,unlock_level,'text','flavor_text'),
    ('PowerShard','Power Shard',2,unlock_level,'text','flavor_text'),
    ('RemoveOne','Remove One',3,unlock_level,'text','flavor_text'),
    ('RescueBadge','Rescue Badge',3,unlock_level,'text','flavor_text'),
    ('Riffle','Riffle',1,unlock_level,'text','flavor_text'),
    ('RockTumbler','Rock Tumbler',1,unlock_level,'text','flavor_text'),
    ('RollerBlades','Roller Blades',3,unlock_level,'text','flavor_text'),
    ('Rose','Rose',2,unlock_level,'text','flavor_text'),
    ('Ruby','Ruby',3,unlock_level,'text','flavor_text'),
    ('SaigonArmor','Saigon Armor',3,unlock_level,'text','flavor_text'),
    ('Satellite','Satellite',3,unlock_level,'text','flavor_text'),
    ('Scales','Scales',1,unlock_level,'text','flavor_text'),
    ('SecondBreakfast','Second Breakfast',1,unlock_level,'text','flavor_text'),
    ('ShieldBattery','Shield Battery',2,unlock_level,'text','flavor_text'),
    ('Sinkhole','Sinkhole',1,unlock_level,'text','flavor_text'),
    ('SoulFood','Soul Food',3,unlock_level,'text','flavor_text'),
    ('PetSoulGun','Soul Gun',3,unlock_level,'text','flavor_text'),
    ('SpeedLoader','Speed Loader',3,unlock_level,'text','flavor_text'),
    ('SpikeProtein','Spike Protein',1,unlock_level,'text','flavor_text'),
    ('Static','Static',2,unlock_level,'text','flavor_text'),
    ('StepDrone','Step Drone',3,unlock_level,'text','flavor_text'),
    ('Stimpack','Stimpack',2,unlock_level,'text','flavor_text'),
    ('SugarGlass','Sugar Glass',1,unlock_level,'text','flavor_text'),
    ('Sunglasses','Sunglasses',2,unlock_level,'text','flavor_text'),
    ('SurvivalKit','Survival Kit',1,unlock_level,'text','flavor_text'),
    ('Symbiosis','Symbiosis',1,unlock_level,'text','flavor_text'),
    ('Thermite','Thermite',3,unlock_level,'text','flavor_text'),
    ('Thermophage','Thermophage',1,unlock_level,'text','flavor_text'),
    ('Thornmail','Thornmail',1,unlock_level,'text','flavor_text'),
    ('TightPants','Tight Pants',4,unlock_level,'text','flavor_text'),
    ('Tinder','Tinder',4,unlock_level,'text','flavor_text'),
    ('Transmission','Transmission',2,unlock_level,'text','flavor_text'),
    ('TrapCard','Trap Card',4,unlock_level,'text','flavor_text'),
    ('Trinket','Trinket',3,unlock_level,'text','flavor_text'),
    ('Trident','Trident',1,unlock_level,'text','flavor_text'),
    ('Tutu','Tutu',1,unlock_level,'text','flavor_text'),
    ('Umbrella','Umbrella',1,unlock_level,'text','flavor_text'),
    ('Undershirt','Undershirt',2,unlock_level,'text','flavor_text'),
    ('UpgradeOne','Upgrade One',3,unlock_level,'text','flavor_text'),
    ('Uranium','Uranium',3,unlock_level,'text','flavor_text'),
    ('VGunMod','VGun',4,unlock_level,'text','flavor_text'),
    ('Violet','Violet',2,unlock_level,'text','flavor_text'),
    ('ViralTransmitter','Viral Transmitter',1,unlock_level,'text','flavor_text'),
    ('Virtue','Virtue',3,unlock_level,'text','flavor_text'),
    ('WaterWheel','Water Wheel',1,unlock_level,'text','flavor_text'),
    ('Wings','Wings',4,unlock_level,'text','flavor_text'),
    ('XD40','XD-40',1,unlock_level,'text','flavor_text'),
    ('ZCell','Z-Cell',2,unlock_level,'text','flavor_text')
    ;


