/*
('id','name',rarity,unlock_level,'text','flavor_text')
ordered by level obtained on https://onestepfromeden.fandom.com/wiki/Artifacts
*/
INSERT INTO osfe_spells
VALUES 
    ('Bulwark ','Bulwark ',rarity,unlock_level,'text','flavor_text'),
    ('Citrine','Citrine',rarity,unlock_level,'text','flavor_text'),
    ('CoverFire','name',rarity,unlock_level,'text','flavor_text'),
    ('HeartOfTheCards','name',rarity,unlock_level,'text','flavor_text'),
    ('Moonstone','name',rarity,unlock_level,'text','flavor_text'),
    ('SubTank','name',rarity,unlock_level,'text','flavor_text'),
    ('PetDragon','Pet Dragon',rarity,unlock_level,'text','flavor_text'),
    ('MoltenCore','name',rarity,unlock_level,'text','flavor_text'),
    ('Frostmail','Frostmail',rarity,unlock_level,'text','flavor_text'),
    ('Icing','Icing',rarity,unlock_level,'text','flavor_text'),
    ('SnowBoots','Snow Boots',rarity,unlock_level,'text','flavor_text'),
    ('ColdPressedJuice','Cold Pressed Juice',rarity,unlock_level,'text','flavor_text'),
    ('HardenedShields','Hardened Shields',rarity,unlock_level,'text','flavor_text'),
    ('Acupuncture','Acupuncture',rarity,unlock_level,'text','flavor_text'),
    ('GripTape','Grip Tape',rarity,unlock_level,'text','flavor_text'),
    ('MasonJar','Masonjar',rarity,unlock_level,'text','flavor_text'),
    ('CassidyScarf','Cassidy\'s Scarf',rarity,unlock_level,'text','flavor_text'),
    ('Ninjutsu','Ninjutsu',rarity,unlock_level,'text','flavor_text'),
    ('ImmuneSystem','Immune System',rarity,unlock_level,'text','flavor_text'),
    ('ShadowToxin','Shadow Toxin',rarity,unlock_level,'text','flavor_text'),
    ('ResistantStrain','Resistant Strain',rarity,unlock_level,'text','flavor_text'),
    ('ChaosFrag','Chaos Fragment',rarity,unlock_level,'text','flavor_text'),
    ('DartFrog','Dart Frog',rarity,unlock_level,'text','flavor_text'),
    ('Thorn','Thorn',rarity,unlock_level,'text','flavor_text'),
    ('UnicornBomb','Unicorn Bomb',rarity,unlock_level,'text','flavor_text'),
    ('Vaccine','Vaccine',rarity,unlock_level,'text','flavor_text'),
    ('Flechette','Flechette',rarity,unlock_level,'text','flavor_text'),
    ('PetKitty','Pet Kitty',rarity,unlock_level,'text','flavor_text'),
    ('PocketSand','Pocket Sand',rarity,unlock_level,'text','flavor_text'),
    ('PhasePlates','Phase Plates',rarity,unlock_level,'text','flavor_text'),
    ('Daffodil','Daffodil',rarity,unlock_level,'text','flavor_text'),
    ('Lilac','Lilac',rarity,unlock_level,'text','flavor_text'),
    ('SpellthiefLicense','Spellthief License',rarity,unlock_level,'text','flavor_text'),
    ('Stoplight','Stoplight',rarity,unlock_level,'text','flavor_text'),
    ('Tessellate','Tessellate',rarity,unlock_level,'text','flavor_text'),
    ('CandyWrapper','Candy Wrapper',rarity,unlock_level,'text','flavor_text'),
    ('Mother','Mother',rarity,unlock_level,'text','flavor_text'),
    ('Trifrost','Trifrost',rarity,unlock_level,'text','flavor_text'),
    ('DuelDisk','Duel Disk',rarity,unlock_level,'text','flavor_text'),
    ('Goldfish','Goldfish',rarity,unlock_level,'text','flavor_text'),
    ('PetFox','Pet Fox',rarity,unlock_level,'text','flavor_text'),
    ('Transcendence','Transcendence',rarity,unlock_level,'text','flavor_text'),
/* no levels entered in below blob */
    ('ThreeDPrinter','3D Printer',rarity,unlock_level,'text','flavor_text'),
    ('AdaptiveArmor','Adaptive Armor',rarity,unlock_level,'text','flavor_text'),
    ('Adrenaline','Adrenaline',rarity,unlock_level,'text','flavor_text'),
    ('Aether','Aether',rarity,unlock_level,'text','flavor_text'),
    ('Amethyst','Amethyst',rarity,unlock_level,'text','flavor_text'),
    ('Anthrax','Anthrax',rarity,unlock_level,'text','flavor_text'),
    ('Anvil','Anvil',rarity,unlock_level,'text','flavor_text'),
    ('Bandage','Bandage',rarity,unlock_level,'text','flavor_text'),
    ('BazsWhip','Baz\'s Whip',rarity,unlock_level,'text','flavor_text'),
    ('Beaker','Beaker',rarity,unlock_level,'text','flavor_text'),
    ('Beret','Beret',rarity,unlock_level,'text','flavor_text'),
    ('Bismuth','Bismuth',rarity,unlock_level,'text','flavor_text'),
    ('BlazeOfGlory','Blaze Of Glory',rarity,unlock_level,'text','flavor_text'),
    ('BloodMoney','Blood Money',rarity,unlock_level,'text','flavor_text'),
    ('BlueBlood','Blue Blood',rarity,unlock_level,'text','flavor_text'),
    ('BlueFlame','Blue Flame',rarity,unlock_level,'text','flavor_text'),
    ('BlueberryJam','Blueberry Jam',rarity,unlock_level,'text','flavor_text'),
    ('BoltAction','Bolt Action',rarity,unlock_level,'text','flavor_text'),
    ('Bubble','Bubble',rarity,unlock_level,'text','flavor_text'),
    ('CardThrower','Card Thrower',rarity,unlock_level,'text','flavor_text'),
    ('CensorBar','Censor Bar',rarity,unlock_level,'text','flavor_text'),
    ('Chalice','Chalice',rarity,unlock_level,'text','flavor_text'),
    ('ChocoMintChip','Choco Mint Chip',rarity,unlock_level,'text','flavor_text'),
    ('CobraCare','Cobra Care',rarity,unlock_level,'text','flavor_text'),
    ('ColdBlooded','Cold Blooded',rarity,unlock_level,'text','flavor_text'),
    ('CoolShoes','Cool Shoes',rarity,unlock_level,'text','flavor_text'),
    ('CreditCard','Credit Card',rarity,unlock_level,'text','flavor_text'),
    ('Cryophage','Cryophage',rarity,unlock_level,'text','flavor_text'),
    ('Curacao','Curacao',rarity,unlock_level,'text','flavor_text'),
    ('Delta','Delta',rarity,unlock_level,'text','flavor_text'),
    ('DoubleEdge','Double Edge',rarity,unlock_level,'text','flavor_text'),
    ('DoubleMint','Double Mint',rarity,unlock_level,'text','flavor_text'),
    ('DuctTape','Duct Tape',rarity,unlock_level,'text','flavor_text'),
    ('Elysium','Elysium',rarity,unlock_level,'text','flavor_text'),
    ('EmptyBottle','Empty Bottle',rarity,unlock_level,'text','flavor_text'),
    ('Eschaton','Eschaton',rarity,unlock_level,'text','flavor_text'),
    ('ExplosiveTendons','Explosive Tendons',rarity,unlock_level,'text','flavor_text'),
    ('Feather','Feather',rarity,unlock_level,'text','flavor_text'),
    ('FlakJacket','Flak Jacket',rarity,unlock_level,'text','flavor_text'),
    ('FlashLoader','Flash Loader',rarity,unlock_level,'text','flavor_text'),
    ('Fragment','Fragment',rarity,unlock_level,'text','flavor_text'),
    ('FreezerBurn','Freezer Burn',rarity,unlock_level,'text','flavor_text'),
    ('Gelatin','Gelatin',rarity,unlock_level,'text','flavor_text'),
    ('GhostCostume','Ghost Costume',rarity,unlock_level,'text','flavor_text'),
    ('GiantArmor','Giant Armor',rarity,unlock_level,'text','flavor_text'),
    ('GlassCannon','Glass Cannon',rarity,unlock_level,'text','flavor_text'),
    ('Champagne','Glass Flute',rarity,unlock_level,'text','flavor_text'),
    ('GoldenCat','Golden Cat',rarity,unlock_level,'text','flavor_text'),
    ('Granite','Granite',rarity,unlock_level,'text','flavor_text'),
    ('Harpoon','Harpoon',rarity,unlock_level,'text','flavor_text'),
    ('HeartOfGold','Heart of Gold',rarity,unlock_level,'text','flavor_text'),
    ('HexBadge','Hex Badge',rarity,unlock_level,'text','flavor_text'),
    ('HitSeeker','Hit Seeker',rarity,unlock_level,'text','flavor_text'),
    ('HoningSteel','Honing Steel',rarity,unlock_level,'text','flavor_text'),
    ('IceFloe','Ice Floe',rarity,unlock_level,'text','flavor_text'),
    ('IceSculpture','Ice Sculpture',rarity,unlock_level,'text','flavor_text'),
    ('Kabob','Kabob',rarity,unlock_level,'text','flavor_text'),
    ('KineticShield','Kinetic Shield',rarity,unlock_level,'text','flavor_text'),
    ('KnifeBelt','Knife Belt',rarity,unlock_level,'text','flavor_text'),
    ('LaserPointer','Laser Pointer',rarity,unlock_level,'text','flavor_text'),
    ('LifeJacket','Life Jacket',rarity,unlock_level,'text','flavor_text'),
    ('Lily','Lily',rarity,unlock_level,'text','flavor_text'),
    ('LinkCable','Link Cable',rarity,unlock_level,'text','flavor_text'),
    ('LongSleeves','Long Sleeves',rarity,unlock_level,'text','flavor_text'),
    ('LuckBox','Luck Box',rarity,unlock_level,'text','flavor_text'),
    ('LuckyCoin','Lucky Coin',rarity,unlock_level,'text','flavor_text'),
    ('Luna','Luna',rarity,unlock_level,'text','flavor_text'),
    ('GunnerFrontAll','M1 Liofire (Artifact)',rarity,unlock_level,'text','flavor_text'),
    ('GunnerHoming','M2 Hunter Seeker (Artifact)',rarity,unlock_level,'text','flavor_text'),
    ('MagnifyingGlass','Magnifying Glass',rarity,unlock_level,'text','flavor_text'),
    ('ManaGem','Mana Gem',rarity,unlock_level,'text','flavor_text'),
    ('ManaVein','Mana Vein',rarity,unlock_level,'text','flavor_text'),
    ('ManaJam','Manajam',rarity,unlock_level,'text','flavor_text'),
    ('MeatShield','Meat Shield',rarity,unlock_level,'text','flavor_text'),
    ('Medkit','Medkit',rarity,unlock_level,'text','flavor_text'),
    ('MeritBadge','Merit Badge',rarity,unlock_level,'text','flavor_text'),
    ('MicroMissiles','Micro Missiles',rarity,unlock_level,'text','flavor_text'),
    ('MiningRig','Mining Rig',rarity,unlock_level,'text','flavor_text'),
    ('MintTea','Mint Tea',rarity,unlock_level,'text','flavor_text'),
    ('Miracle','Miracle',rarity,unlock_level,'text','flavor_text'),
    ('Mirror','Mirror',rarity,unlock_level,'text','flavor_text'),
    ('Mitosis','Mitosis',rarity,unlock_level,'text','flavor_text'),
    ('Mjolnir','Mjolnir',rarity,unlock_level,'text','flavor_text'),
    ('Monocle','Monocle',rarity,unlock_level,'text','flavor_text'),
    ('Multitool','Multitool',rarity,unlock_level,'text','flavor_text'),
    ('MuzzleBrake','Muzzle Brake',rarity,unlock_level,'text','flavor_text'),
    ('NerveGas','Nerve Gas',rarity,unlock_level,'text','flavor_text'),
    ('PantherHabit','Panther Habit',rarity,unlock_level,'text','flavor_text'),
    ('PaperWallet','Paper Wallet',rarity,unlock_level,'text','flavor_text'),
    ('Pendulum','Pendulum',rarity,unlock_level,'text','flavor_text'),
    ('PetLiger','Pet Liger',rarity,unlock_level,'text','flavor_text'),
    ('PetPuppy','Pet Puppy',rarity,unlock_level,'text','flavor_text'),
    ('PetTurtle','Pet Turtle',rarity,unlock_level,'text','flavor_text'),
    ('PiggyBank','Piggy Bank',rarity,unlock_level,'text','flavor_text'),
    ('Pinwheel','Pinwheel',rarity,unlock_level,'text','flavor_text'),
    ('PocketWatch','Pocket Watch',rarity,unlock_level,'text','flavor_text'),
    ('PoisonVial','Poison Vial',rarity,unlock_level,'text','flavor_text'),
    ('PowerShard','Power Shard',rarity,unlock_level,'text','flavor_text'),
    ('RemoveOne','Remove One',rarity,unlock_level,'text','flavor_text'),
    ('RescueBadge','Rescue Badge',rarity,unlock_level,'text','flavor_text'),
    ('Riffle','Riffle',rarity,unlock_level,'text','flavor_text'),
    ('RockTumbler','Rock Tumbler',rarity,unlock_level,'text','flavor_text'),
    ('RollerBlades','Roller Blades',rarity,unlock_level,'text','flavor_text'),
    ('Rose','Rose',rarity,unlock_level,'text','flavor_text'),
    ('Ruby','Ruby',rarity,unlock_level,'text','flavor_text'),
    ('SaigonArmor','Saigon Armor',rarity,unlock_level,'text','flavor_text'),
    ('Satellite','Satellite',rarity,unlock_level,'text','flavor_text'),
    ('Scales','Scales',rarity,unlock_level,'text','flavor_text'),
    ('SecondBreakfast','Second Breakfast',rarity,unlock_level,'text','flavor_text'),
    ('ShieldBattery','Shield Battery',rarity,unlock_level,'text','flavor_text'),
    ('Sinkhole','Sinkhole',rarity,unlock_level,'text','flavor_text'),
    ('SoulFood','Soul Food',rarity,unlock_level,'text','flavor_text'),
    ('PetSoulGun','Soul Gun',rarity,unlock_level,'text','flavor_text'),
    ('SpeedLoader','Speed Loader',rarity,unlock_level,'text','flavor_text'),
    ('SpikeProtein','Spike Protein',rarity,unlock_level,'text','flavor_text'),
    ('Static','Static',rarity,unlock_level,'text','flavor_text'),
    ('StepDrone','Step Drone',rarity,unlock_level,'text','flavor_text'),
    ('Stimpack','Stimpack',rarity,unlock_level,'text','flavor_text'),
    ('SugarGlass','Sugar Glass',rarity,unlock_level,'text','flavor_text'),
    ('Sunglasses','Sunglasses',rarity,unlock_level,'text','flavor_text'),
    ('SurvivalKit','Survival Kit',rarity,unlock_level,'text','flavor_text'),
    ('Symbiosis','Symbiosis',rarity,unlock_level,'text','flavor_text'),
    ('Thermite','Thermite',rarity,unlock_level,'text','flavor_text'),
    ('Thermophage','Thermophage',rarity,unlock_level,'text','flavor_text'),
    ('Thornmail','Thornmail',rarity,unlock_level,'text','flavor_text'),
    ('TightPants','Tight Pants',rarity,unlock_level,'text','flavor_text'),
    ('Tinder','Tinder',rarity,unlock_level,'text','flavor_text'),
    ('Transmission','Transmission',rarity,unlock_level,'text','flavor_text'),
    ('TrapCard','Trap Card',rarity,unlock_level,'text','flavor_text'),
    ('Trinket','Trinket',rarity,unlock_level,'text','flavor_text'),
    ('Trident','Trident',rarity,unlock_level,'text','flavor_text'),
    ('Tutu','Tutu',rarity,unlock_level,'text','flavor_text'),
    ('Umbrella','Umbrella',rarity,unlock_level,'text','flavor_text'),
    ('Undershirt','Undershirt',rarity,unlock_level,'text','flavor_text'),
    ('UpgradeOne','Upgrade One',rarity,unlock_level,'text','flavor_text'),
    ('Uranium','Uranium',rarity,unlock_level,'text','flavor_text'),
    ('VGunMod','VGun',rarity,unlock_level,'text','flavor_text'),
    ('Violet','Violet',rarity,unlock_level,'text','flavor_text'),
    ('ViralTransmitter','Viral Transmitter',rarity,unlock_level,'text','flavor_text'),
    ('Virtue','Virtue',rarity,unlock_level,'text','flavor_text'),
    ('WaterWheel','Water Wheel',rarity,unlock_level,'text','flavor_text'),
    ('Wings','Wings',rarity,unlock_level,'text','flavor_text'),
    ('XD40','XD-40',rarity,unlock_level,'text','flavor_text'),
    ('ZCell','Z-Cell',rarity,unlock_level,'text','flavor_text')
    ;


